### ISSUE TITLE
pattern not matched with data

### ISSUE THREAD

**Issue by caipengtao** [banzaicloud/logging-operator#1005]
Inserting a record into the file every second, resulting in an error "pattern not matched with data", If the insert every five seconds is successful.

the script:
```
for i in `seq 100`;do
echo '{"log":"{\"name\":\"h1\",\"timestamp\":\"2022-05-09T09:12:00\"}","stream":"stdout","time":"2022-05-09T09:02:00.264943487Z"}' >> /var/log/containers/nginx-6cb9bc449c-flnjl_logging_nginx-1e10d5cde1b97c4aaf84920816f57d793e7048477a7b9f417da707c86243dac5.log
sleep 1
done
```

The error:
![image](https://user-images.githubusercontent.com/19907364/167404046-fa828379-f939-4c09-9902-b7b6208aa929.png)

the flow
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: default-flow
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        parse:
          type: json
  localOutputRefs:
    - elasticsearch-output
  match:
    - select:
        labels:
          app.kubernetes.io/name: log-generator
```
the output
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: elasticsearch-output
spec:
  elasticsearch:
    host: 172.20.11.25
    port: 9200
    scheme: http
    index_name: fluentd-es
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
```

the fluentbit and fluentd
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging
spec:
  controlNamespace: logging
  fluentbit:
    inputTail:
      Skip_Long_Lines: "true"
      Parser: docker
      Refresh_Interval: "60"
      Rotate_Wait: "5"
      Mem_Buf_Limit: "128M"
      Docker_Mode: "true"
    bufferStorage:
      storage.backlog.mem_limit: 10M
      storage.path: /var/log/logging/fluentbit-buffer
    bufferStorageVolume:
      hostPath:
        path: "/var/log/logging/fluentbit-buffer"
    positiondb:
      hostPath:
        path: "/var/log/logging/positiondb"
    image:
      repository: fluent/fluent-bit
      tag: 1.8.15
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 1000m
        memory: 512Mi
    security:
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      podSecurityContext:
        fsGroup: 101
    forwardOptions:
      Require_ack_response: true
    network:
      connectTimeout: 30
      keepaliveIdleTimeout: 60
    enableUpstream: true
  fluentd:
    disablePvc: true
    bufferStorageVolume:
      emptyDir: {}
    fluentOutLogrotate:
      enabled: true
      path: /fluentd/log/out
      age: "10"
      size: "10485760"
    scaling:
      replicas: 1
    workers: 1
    image:
      repository: ghcr.io/banzaicloud/fluentd
      tag: v1.14.6-alpine-3
      pullPolicy: IfNotPresent
```
