### ISSUE TITLE
buffer-metrics-sidecar: command node_exporter not found

### ISSUE THREAD

**Issue by h4wkmoon** [banzaicloud/logging-operator#1013]
Hi, 
**Describe the bug**:
The buffer-metrics-sidecar of the fluentds pods shows the error msg : 
 
```
listening on port:7357
sh: ./bin/node_exporter --web.listen-address=:9200 --collector.disable-defaults --collector.filesystem: not found
```

**Expected behaviour**:
```
listening on port:7357
ts=2022-05-20T09:40:26.195Z caller=node_exporter.go:182 level=info msg="Starting node_exporter" version="(version=1.3.1, branch=HEAD, revision=a2321e7b940ddcff26873612bccdf7cd4c42b6b6)"
ts=2022-05-20T09:40:26.195Z caller=node_exporter.go:183 level=info msg="Build context" build_context="(go=go1.17.3, user=root@243aafa5525c, date=20211205-11:09:49)"
ts=2022-05-20T09:40:26.195Z caller=node_exporter.go:108 level=info msg="Enabled collectors"
ts=2022-05-20T09:40:26.195Z caller=node_exporter.go:199 level=info msg="Listening on" address=:9200
ts=2022-05-20T09:40:26.195Z caller=tls_config.go:195 level=info msg="TLS is disabled." http2=false
```

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.20.8
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Rancher
- logging-operator version (e.g. 2.1.1): 3.17.5
- Install method (e.g. helm or static manifests): helm with argocd
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

 ```
       fluentd:
          logLevel: info
          metrics:
            serviceMonitor: true
            prometheusRules: false
          resources: {"limits": {"cpu": 2, "memory": "2Gi"}, "requests": {"cpu": "500m", "memory": "500Mi"}}
          image:
            repository: "[redacted]/banzaicloud/fluentd"
            tag: v1.14.6-alpine-4
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: "app.kubernetes.io/component"
                      operator: In
                      values:
                      - "fluentd"
                  topologyKey: kubernetes.io/hostname
          bufferStorageVolume:
            pvc:
              spec:
                storageClassName: azuredisk-premium-lrs
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 40Gi
```

/kind bug

Runnng the container by itself on a docker machine, I can't reproduce the bug unless I use non-breakable spaces in the node_exporter command and parameters. I can't think of a reason why non-breakable spaces would be used in the operator. There must be another root cause.
