### ISSUE TITLE
Allow configuring the docker image used by eventtailer 

### ISSUE THREAD

**Issue by aslafy-z** [banzaicloud/logging-operator#1046]
**Is your feature request related to a problem? Please describe.**
In a air-gapped system, images cannot be pulled from docker hub.

**Describe the solution you'd like**
Allow overriding the eventtailer docker image.

**Describe alternatives you've considered**
Mutation via Kyverno: not an elegant option

**Additional context**
See hardcoded image at https://github.com/banzaicloud/logging-operator/blob/4218d98bb104b816cf634519103fd53848a49f91/pkg/resources/eventtailer/statefulset.go#L63

**Comment by Lamovich** [comment]
Hi. i use helm and app 3.17.7
Just added  "containerOverrides" to templates/eventailer.yaml 

```
{{- with $.Values.eventTailer }}
apiVersion: logging-extensions.banzaicloud.io/v1alpha1
kind: EventTailer
metadata:
  name: {{ .name | default "event-tailer" }}
spec:
  controlNamespace: {{ $.Values.controlNamespace | default $.Release.Namespace }}
  containerOverrides:
      image: {{ $.Values.eventTailer.image }}
....
....
```

in values.yaml
```
eventTailer:
  image: <your_private_registry>/eventrouter:v0.1.0
```
