### ISSUE TITLE
Documentation for extraVolumes option

### ISSUE THREAD

**Issue by abierbaum** [banzaicloud/logging-operator#1057]
**Is your feature request related to a problem? Please describe.**

I would like to see documentation or an example added showing how to use the `extraVolumes` configuration with the `Logging` CRD and fluentd.  

**Describe the solution you'd like**

An example of how to correctly configure it similar to what is shown here: https://banzaicloud.com/docs/one-eye/logging-operator/configuration/fluentd/  for `bufferStorageVolume`.

**Describe alternatives you've considered**

I searched the source code, issues, and example and didn't find a place this is documented.  Also looked through the CRD definition file.

**Additional context**

I tried creating it the best I could and came up with something like below.  But when attempting to use it can't start fluentd.  I thought about filing a bug, but this isn't really a bug.  It is just a nice feature that isn't clear how to configure, so I think a documentation or example would be good.

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-demo
  namespace: logging
spec:
  controlNamespace: logging
  fluentbit:
    tls:
      enabled: true
      secretName: logging-demo-fluentbit-tls
      sharedKey: ""
  fluentd:
    logLevel: debug
    tls:
      enabled: true
      secretName: logging-demo-fluentd-tls
      sharedKey: ""
    extraVolumes:
      - path: "/data"
        containerName: fluentd
        volume:
          pvc:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 30Gi
              storageClassName: logging-storage
              volumeMode: Filesystem
```

**Comment by aslafy-z** [comment]
An helpful example could be configuring fluentd to store discarded chunks (`/tmp/fluent/backup`) in a PVC instead of on the host (ephemeral-config).

**Comment by abierbaum** [comment]
@aslafy-z Do you have an example of a working configuration for extraVolumes?  I never got past that point and instead started misusing the buffer volumes configuration instead.

**Comment by aslafy-z** [comment]
Ow, so I misread your issue from the beginning. I thought this example was working on your side and you created this issue to track the addition of this extraVolumes key to the documentation. My bad :sweat_smile:

So I guess you hit the same issue as I reported in https://github.com/banzaicloud/logging-operator/issues/1063 isn't it? It's not working on my side either.

**Comment by starbops** [comment]
I ran into this as well recently. I want to add an extra volume to hold the log archives with file output. I can only create a PVC manually, along with the `source` directive under `extraVolumes` as a workaround. Here's my working example:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-archive
  namespace: logging
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
```

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-infra
  namespace: logging
spec:
  fluentd:
    disablePvc: true
    extraVolumes:
    - volumeName: log-archive
      path: /archive
      containerName: fluentd
      volume:
        pvc:
          source:
            claimName: log-archive
            readOnly: false
          #spec:
          #  accessModes:
          #  - ReadWriteOnce
          #  resources:
          #    requests:
          #      storage: 1Gi
          #  storageClassName: longhorn
          #  volumeMode: Filesystem
    fluentOutLogrotate:
      enabled: true
      path: /fluentd/log/out
      age: "10"
      size: "10485760"
  fluentbit: {}
  controlNamespace: logging
```
