### ISSUE TITLE
eventTailer helm template storageClass definition "bugged"

### ISSUE THREAD

**Issue by schmittse** [banzaicloud/logging-operator#1061]
**Describe the bug**:
If you apply the given configuration exemple for eventTailer :
```yaml
eventTailer:
  pvc:
    accessModes:
      - ReadWriteOnce
    storage: 4Gi
    storageClass: "test"
```
you will get an error message upon install ".storageClass not allowed for type string" (sorry I lost the exact message)

In order to get it working, you need to write the folowing values :
```yaml
eventTailer:
  pvc:
    accessModes:
      - ReadWriteOnce
    storage: 4Gi
    storageClass: 
      storageClass: "test"
```

**Expected behaviour**:
You should not have to repeat the storageClass parameter.

**Additional context**:
The bug is in the eventtailer.yaml template :
```yaml
25: {{- with .storageClass }}
26:        storageClassName: {{ .storageClass }}
27: {{- end
```

It should rather be :
```yaml
25: {{- with .storageClass }}
26:        storageClassName: {{ . }}
27: {{- end
```
(not tested but should work)

**Environment details**:
- Kubernetes version : 1.21.5
- Cloud-provider/provisioner : OnPrem
- logging-operator version : 3.17.8
- Install method : helm over ArgoCD

/kind bug
