### ISSUE TITLE
S3 logging should work with custom endpoints (e.g. Minio)

### ISSUE THREAD

**Issue by onpaws** [banzaicloud/logging-operator#1097]
**Describe the bug**:
Banzai logging operator `Output` [supports S3](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/s3/#output-config-s3_endpoint). 
However, pointing to custom S3 endpoints (e.g. an S3 endpoint _not_ hosted at AWS) does not appear to work.

<details>
<summary>example manifest</summary>

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  annotations:
    field.cattle.io/description: OVH Object Storage PoC
  name: ovh-banzai-objectstorage-output
spec:
  s3:
    aws_key_id:
      valueFrom:
        secretKeyRef:
          key: accessKeyId
          name: logging-ovh-s3
    aws_sec_key:
      valueFrom:
        secretKeyRef:
          key: secretAccesKey
          name: logging-ovh-s3
    s3_bucket: mybucket
    s3_endpoint: https://storage.gra.cloud.ovh.net/
    s3_region: gra
status:
  active: true
```

</details>

**Expected behaviour**:
Logs should ship to the custom S3 endpoint.

**Steps to reproduce the bug**:
Setup Banzai operator, create a `Flow`, and create an `Output` pointing to a custom, non AWS-hosted S3 endpoint like above.

**Additional context**:
I noticed the URL the underlying `aws-s3-sdk` Ruby gem tries to connect to, seems potentially wrong. Not 100% sure.
![image](https://user-images.githubusercontent.com/182515/188895229-3a948c68-fb62-43af-86c4-2fede03e9418.png)

Minimum needed code to repro:
```ruby
require 'aws-sdk-s3'

options = {}
options[:access_key_id] = "SNIP"
options[:secret_access_key] = "SNIP"
options[:endpoint] = "https://storage.gra.cloud.ovh.net"
options[:region] = "gra"

s3_client = Aws::S3::Client.new(options)
@s3 = Aws::S3::Resource.new(client: s3_client)
@bucket = @s3.bucket('mybucket')
print('exists?', @bucket.exists?)
```

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.20.14
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Hetzner + RKE
- logging-operator version (e.g. 2.1.1): 3.8.2
- Install method (e.g. helm or static manifests): Rancher
- Logs from the misbehaving component (and any other relevant logs):
  - `2022-09-06 13:42:38 +0000 [error]: fluent/log.rb:371:error: unexpected error error_class=Aws::S3::Errors::Http405Error error="Aws::S3::Errors::Http405Error"`

- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
see above

/kind bug
