### ISSUE TITLE
Logging operator don't create log group on CloudWatch

### ISSUE THREAD

**Issue by mamu-reply** [banzaicloud/logging-operator#1121]
**Describe the Problem**:
After installing the two helm charts (logging-operator & logging-operator-logging) on my EKS, and configured them to send logs to AWS CloudWatch, on the AWS side I don't see the log group that it should have created.
Instead, going to see the status of the logging operator, everything is perfectly up and running, and the logs do not bring any errors or warnings

**Expected behaviour**:
After configuring everything following the example of the official [guide](https://banzaicloud.com/docs/one-eye/logging-operator/quickstarts/cloudwatch-nginx/) I expect the log group to be created with the log stream on AWS CloudWatch, but it doesn't happen.

**Steps to reproduce the Problem**:
My values configuration is this for the **logging-operator-logging**:
```
  controlNamespace: logging-operator
  allowClusterResourcesFromAllNamespaces: true
  fluentbit: {}
  fluentd: {}
  tls:
    enabled: false

  #### clusterFlows ####
  clusterFlows:
    - name: all-pods
      spec:
        globalOutputRefs:
          - cloudwatch
        match:
          - select: {}

  #### clusterOutputs ####
  clusterOutputs:
    - name: cloudwatch
      spec:
        cloudwatch:
          aws_key_id:
            valueFrom:
              secretKeyRef:
                name: logging-cloudwatch
                key: awsAccessKeyId
          aws_sec_key:
            valueFrom:
              secretKeyRef:
                name: logging-cloudwatch
                key: awsSecretAccessKey
          log_group_name: operator-log-group
          log_stream_name: operator-log-stream
          region: eu-central-1
          auto_create_stream: true
          buffer:
            timekey: 30s
            timekey_wait: 30s
            timekey_use_utc: true
```

I've also tried to add this two:
```
   aws_use_sts: true
       aws_sts_role_arn: "arn:####ROLE_THAT_ALLOW_ALL####"
```
For the **logging-operator** helm chart i've used the default values, but i've also tried to add this:
```
   serviceAccount:
       annotations:
          eks.amazonaws.com/role-arn: "arn:####ROLE_THAT_ALLOW_ALL####"
```

Then i've tried to do the same with a yamls configuration (both with ClusterFlow and ClusterOutput and with Flow and Output):
```
apiVersion: v1
kind: Secret
metadata:
  name: logging-cloudwatch
  namespace: logging-operator
type: Opaque
data:
  awsAccessKeyId: XXXXXXXXX
  awsSecretAccessKey: YYYYYYYYYYY

---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-sample
  namespace: logging-operator
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: logging-operator

---

apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
 name: cloudwatch-output
 namespace: logging-operator
spec:
 cloudwatch:
   aws_key_id:
     valueFrom:
       secretKeyRef:
         name: logging-cloudwatch
         key: awsAccessKeyId
   aws_sec_key:
     valueFrom:
       secretKeyRef:
         name: logging-cloudwatch
         key: awsSecretAccessKey
   log_group_name: operator-log-group
   log_stream_name: operator-log-stream
   region: eu-central-1
   auto_create_stream: true
   buffer:
     timekey: 30s
     timekey_wait: 30s
     timekey_use_utc: true

---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: cloudwatch-flow
  namespace: logging-operator
spec:
  match:
    - select:
        labels:
          app.kubernetes.io/name: log-generator
  globalOutputRefs:
    - cloudwatch-output

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: log-generator
 namespace: logging-operator
spec:
 selector:
   matchLabels:
     app.kubernetes.io/name: log-generator
 replicas: 1
 template:
   metadata:
     labels:
       app.kubernetes.io/name: log-generator
   spec:
     containers:
     - name: nginx
       image: banzaicloud/log-generator:0.3.2

```

however, nothing happens on the AWS side, someone can help me?

**Environment details**:
- Kubernetes version (e.g. v1.15.2):  1.22
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): 3.17.9
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): I did not see any error logs in the logging-operator pod, nothing arrives on CloudTrail either, I don't know where else to look.
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: Inserted in the problem description.

Thanks

**Comment by mamu-reply** [comment]
I've solved the problem; If you are creating the logging operator inside an EKS to send logs of the EKS to a cloudwatch of the same AWS env, you DON'T have to add AWS keys:
```
   aws_key_id:
     valueFrom:
       secretKeyRef:
         name: logging-cloudwatch
         key: awsAccessKeyId
   aws_sec_key:
     valueFrom:
       secretKeyRef:
         name: logging-cloudwatch
         key: awsSecretAccessKey
```
