### ISSUE TITLE
Set dynamic logstash_prefix for elasticsearch output

### ISSUE THREAD

**Issue by vitalyl1343** [banzaicloud/logging-operator#1125]
I want to configure ClusterOutput to forward log to ES cluster based on k8s labels& 
I tried this configuration:

ClusterOutput:

`apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: test-output
  namespace: logging
spec:
  elasticsearch:
    buffer:
      chunk_limit_size: 100MB
      retry_forever: false
      retry_max_times: 3
      tags: tag
      timekey: 1m
      timekey_use_utc: true
      timekey_wait: 30s
    exception_backup: false
    host: myhost.com
    include_timestamp: true
    log_es_400_reason: true
    #ogstash_format: true
    logstash_prefix: testprefix-${logger_index_name}
`

ClusterFlow:

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: test-clusterflow
  namespace: logging
spec:
  filters:
  - parser:
      key_name: message
      parse:
        patterns:
        - format: json
          time_format: '%iso8601'
          time_key: time
          time_type: string
  - record_modifier:
      records:
        - logger_index_name: ${record.dig('kubernetes', 'labels', 'logger_index_name') || "unknown"}
  globalOutputRefs:
  - test-output
```
Then I deployed application with label logger_index_name: test-application

**Expected behaviour**:
I expect documents with index testprefix-test-application-2022-10-26 but I've received docs with index testprefix-${logger_index_name}-2022-10-26

**Environment details**:
- logging-operator version 3.17.7:

/kind bug
