### ISSUE TITLE
flow grep filter exclude bug

### ISSUE THREAD

**Issue by ekhaydarov** [banzaicloud/logging-operator#1171]
**Describe the bug**:
setting a fluentd filter in the logging-operator flow throws an error.
```
error validating data: ValidationError(Flow.spec.filters[2]): unknown field "exclude" in io.banzaicloud.logging.v1beta1.Flow.spec.filters
```
the config is simple
```
        - grep:
          exclude:
          - key: message
            pattern: /level=(?=(debug|info))/
```

**Expected behaviour**:
The helm chart should deploy

**Steps to reproduce the bug**:
use the grep fitler described above

**Additional context**:
Funnily enough the exclude works when its under or
```
        - grep:
           or:
           - exclude:
             - key: message
               pattern: /level=(?=(debug|info))/
```
**Environment details**:
- Kubernetes version 1.24.3:
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AKS
- logging-operator version (e.g. 2.1.1): 3.17.10
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): no logs cant install
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by aslafy-z** [comment]
I see an indentation issue in your example, can you try the following please?

```yaml
        - grep:
            exclude:
            - key: message
              pattern: /level=(?=(debug|info))/
```
