### ISSUE TITLE
PV is not being created

### ISSUE THREAD

**Issue by estahn** [banzaicloud/logging-operator#121]
**Describe the bug**

Error message when looking at the `fluentd` deployment.

![image](https://user-images.githubusercontent.com/362174/62761763-d28b1080-baca-11e9-98b5-73282d8ecde5.png)

```
AttachVolume.Attach failed for volume "pvc-9257a4f3-dc00-11e8-861e-066f61791264" : InvalidVolume.NotFound: The volume 'vol-0e01f05ffc211c477' does not exist. status code: 400, request id: d7130385-fc3e-4070-a0af-d7608e9c634d
Unable to mount volumes for pod "fluentd-77c8668587-szh8k_devops(929cb55f-ba74-11e9-977f-02d8cf9744bc)": timeout expired waiting for volumes to attach or mount for pod "devops"/"fluentd-77c8668587-szh8k". list of unmounted volumes=[buffer]. list of unattached volumes=[config app-config buffer default-token-wxpp9]
```

**To Reproduce**
Helm charts deployed as per instructions.

`helmfile` details:
```yaml
repositories:
  - name: banzaicloud-stable
    url: https://kubernetes-charts.banzaicloud.com
  - name: banzaicloud-incubator
    url: http://kubernetes-charts-incubator.banzaicloud.com

releases:
  - name: banzaicloud-logging-operator
    namespace: devops
    chart: banzaicloud-stable/logging-operator

  - name: banzaicloud-logging-operator-fluent
    namespace: devops
    chart: banzaicloud-stable/logging-operator-fluent
```

**Expected behavior**
Successful deploy without errors.
