### ISSUE TITLE
Catch-all example

### ISSUE THREAD

**Issue by estahn** [banzaicloud/logging-operator#122]
I have configured an nginx specific "Plugin" which is going to ElasticSearch. How do I configure a catch-all to get all the rest?

**Comment by pepov** [comment]
You can set the `pattern` variable for your plugin so that it catches all events that have left in the end. Also you need to give a name that alphabetically comes after all the other plugins as they will be loaded using a glob pattern, which uses alphabetical ordering according to fluentd docs:
https://docs.fluentd.org/configuration/config-file#6-re-use-your-config-the-include-directive

**Comment by estahn** [comment]
@pepov I'm not sure I understand. I have the following configuration, but I don't understand how I get everything else from the cluster send to Humio/Elasticsearch.

```
apiVersion: "logging.banzaicloud.com/v1alpha1"
kind: "Plugin"
metadata:
  name: ingress-nginx-test
  namespace: kube-ingress
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
    k8s-app: nginx-ingress-controller-test
spec:
  input:
    label:
      app: "ingress-nginx-test"
  output:
    - type: "elasticsearch"
      name: humio
      parameters:
        - name: host
          value: "humio-humio-core-es-lb.devops"
        - name: port
          value: "9200"
        - name: scheme
          value: "http"
        - name: user
          value: <username>
        - name: password
          value: ignore
        - name: logstash_format
          value: "true"
        - name: sslVerify
          value: "false"
        - name: sslVersion
          value: "TLSv1_2"

  filter:
    - type: parser
      name: k8s-ingress-nginx-default
      parameters:
        - name: format
          # value: '/^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)"(?:\s+(?<http_x_forwarded_for>[^ ]+))?)?$/'
          # value: '/^(?<host>[^ ]*) -/'
          value: '/^(?<host>[^ ]*) - \[(?<real_ip>[^ ]*)\] - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<last>[^$]*)/'
        - name: timeFormat
          value: "%d/%b/%Y:%H:%M:%S %z"
```

**Comment by estahn** [comment]
I added the following which seems to do what I want:

```
apiVersion: "logging.banzaicloud.com/v1alpha1"
kind: "Plugin"
metadata:
  name: zzz-k8s-catch-all
  namespace: devops
spec:
  input:
    label:
      app: "**.kubernetes"
  output:
    - type: "elasticsearch"
      name: humio
      parameters:
        - name: host
          value: "humio-humio-core-es-lb.devops"
        - name: port
          value: "9200"
        - name: scheme
          value: "http"
        - name: user
          value: ...
        - name: password
          value: ignore
        - name: logstash_format
          value: "true"
        - name: sslVerify
          value: "false"
        - name: sslVersion
          value: "TLSv1_2"
```

**Comment by pepov** [comment]
Yes, so one way to configure the pattern for filters/outputs is using the `input.label.app` field which will be used in the templates like this:
```
<match {{ .pattern }}.**>
```
In addition to that you can override this value per filter/output using the explicit `pattern` parameter:
```
  output:
    - type: "elasticsearch"
      name: humio
      parameters:
        - name: pattern
          value: "*"
        - name: ...
```
With this approach you don't necessarily have to put the catch-all output into a separate plugin, which I suggested earlier, sorry for the confusion.
