### ISSUE TITLE
Geoip module

### ISSUE THREAD

**Issue by estahn** [banzaicloud/logging-operator#123]
**Is your feature request related to a problem? Please describe.**
I would like to use the geoip module.

**Describe the solution you'd like**
```
    - type: geoip
      name: geoip-nginx
      parameters:
        - name: geoip_lookup_keys
          value: host
```
