### ISSUE TITLE
support secrets of type kubernetes.io/tls

### ISSUE THREAD

**Issue by kouk** [banzaicloud/logging-operator#133]
**Is your feature request related to a problem? Please describe.**
The operator doesn't support using TLS with secrets of type `kubernetes.io/tls`, since it generates a deployment and a configmap which assume paths like `serverCert`, while the standard path for this type of secret is `tls.crt`.

**Describe the solution you'd like**
I would like either to be able to optionally generate deployments for fluentd and fluent-bit which project the standard items onto the paths, e.g.
```
      - name: fluent-tls
        secret:
          secretName: lala-fluentd-forward-tls
          items:
          - key: ca.crt
            path: caCert
          - key: tls.crt
            path: clientCert
          - key: tls.key
            path: clientKey
```
or alternatively a way to customize the fluentd and fluent-bit configuration templates to use the standard pathnames.

**Describe alternatives you've considered**
The alternative is to manually generate a generic secret in the way that the operator wants, however i am generating these certificates using cert-manager, which uses the standard `kubernetes.io/tls` type of secret which requires the particular paths to be `tls.key` and `tls.crt`.
