### ISSUE TITLE
Logs are not shipped to fluentd

### ISSUE THREAD

**Issue by Thoro** [banzaicloud/logging-operator#171]
**Describe the bug**

Fluentd stops accepting connections on port 24240 after a few seconds of operation.

I have a simple cluster flow and a simple output flow:

```
kind: ClusterFlow
metadata:
  name: all-log-to-es
  namespace: logging-system
spec:
  filters:
  - tag_normaliser:
      format: ${namespace_name}.${pod_name}.${container_name}
  selectors: {}
  outputRefs:
  - elasticsearch-output
```

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: elasticsearch-output
  namespace: logging-system
spec:
  elasticsearch:
    hosts: elasticsearch.logging.svc.cluster.local.
    port: 9200
    scheme: http
    ssl_verify: false
    include_timestamp: true
    logstash_format: true
    logstash_prefix: kubernetes
    buffer:
      path: /tmp/buffer
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
```

**Steps to reproduce the issue:**

I am not sure if this is reproducable on another cluster - only have one to test here.

I simply created the helm chart and added the two flows described above.

**Expected behavior**

Fluentd continues to handle incoming data.

**Screenshots**

**Additional context**

**Comment by Thoro** [comment]
I'm running kubernetes v1.15.3
Logging-operator in v2.1.1

Logging settings:

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging
spec:
  fluentd:
    disablePvc: true
  fluentbit: {}
  controlNamespace: logging-system
```
