### ISSUE TITLE
Fluentd getting syntax error when pushing to LOKI

### ISSUE THREAD

**Issue by MChorfa** [banzaicloud/logging-operator#178]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
I did the vanilla installation of the operator, fluent(d|bit) with Loki output. but getting :
failed to POST http://loki:3100/api/prom/push
  (500 Internal Server Error parse error at line 1, col 2: syntax error: unexpected }, expecting IDENTIFIER)
**Expected behaviour**:
The log is pushed to Loki 

**Steps to reproduce the bug**:
FLOW:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: app-flow
  namespace: app
spec:
  filters:
    - tag_normaliser: {}
  selectors: {}
  outputRefs:
    - app-output
```
OUTPUT:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: app-output
  namespace: app
spec:
  loki:
    url: http://loki:3100
    buffer:
      path: /tmp/buffer
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
```

**Environment details**:
- Kubernetes version : v1.14.6
- Cloud-provider/provisioner : AZURE
- logging-operator version : 2.1.1 
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
