### ISSUE TITLE
Support time_format for Flow parsers

### ISSUE THREAD

**Issue by nealf** [banzaicloud/logging-operator#192]
**Is your feature request related to a problem? Please describe.**
I'm trying to get the logging-operator to work with `nginx-ingress`, but the default log format is different from the standard `nginx` logs (and thus parser). Using the parse type `regexp` (which is missing from the type documentation) in the `parsers` section of a `Flow`, I can capture the log appropriately, but fluentd fails to parse the log because it doesn't understand the default nginx time format unless explicitly told using the `time_format` field. I can update the `fluentd.conf` file manually after deploying the Flow and everything works as expected.

**Describe the solution you'd like**
Add the `time_format` field to the [list of configurable parse section variables](https://github.com/banzaicloud/logging-operator/blob/chart/logging-operator-logging/2.1.0/docs/plugins/filters/parser.md#parse-section) for a Flow and ClusterFlow CRD. (And update the docs to reflect `regexp` as a valid parse type.)

**Describe alternatives you've considered**
Modifying the config by hand after every Flow update works, but is unsuitable for any real use.

**Additional context**
There are a few other [time parameters](https://docs.fluentd.org/configuration/parse-section#time-parameters) configurable for the parse section. The `time_format` one is the only one I need at the moment, but I don't know if it is worth adding the others at the same time.

Here is an example of what a `Flow` CRD would look like with the `time_format`:

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: nginx-ingress-flow
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        key_name: log
        remove_key_name_field: true
        reserve_data: true
        parsers:
          - type: regexp
            expression: '/^(?<remote_addr>[^ ]*) - \[(?<the_real_ip>)[^ ]*\] - (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*) "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" (?<request_length>[^ ]*) (?<request_time>[^ ]*) \[(?<proxy_upstream_name>[^ ]*)\] \[(?<proxy_alternative_upstream_name>[^ ]*)\] (?<upstream_addr>[^ ]*) (?<upstream_response_length>[^ ]*) (?<upstream_response_time>[^ ]*) (?<upstream_status>[^ ]*) (?<last>[^$]*)/'
            time_key: time
            # New field for time_format
            time_format: '%d/%b/%Y:%H:%M:%S %z'
  selectors:
    app: nginx-ingress
    component: controller
  outputRefs:
    - nginx-ingress-output
```
