### ISSUE TITLE
Using kubernetes labels your extra_labels are overwritten

### ISSUE THREAD

**Issue by Mortega5** [banzaicloud/logging-operator#211]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
Creating an `output` resource setting `configure_kubernetes_labels: true` and `extra_labels`, this field is overwritten using kubernetes labels. 

I found the bug  in [loki.go:93](https://github.com/banzaicloud/logging-operator/blob/58157ed83ca8d38d1aedb981c53bd54e07539f88/pkg/model/output/loki.go#L93). 

**Expected behaviour**:
Add kubernetes labels to `extra_labels` without removing already existing labels

**Steps to reproduce the bug**:
Deploy the following output

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: loki-output-sender
  namespace: monitoring
spec:
  loki:
    url: http://loki:3100
    configure_kubernetes_labels: true
    line_format: json
    extra_labels:
      testing: "testing"
```
If you check the fluentd output it shows:
```
[...]
    @type loki
    @id _loki-flow-monitor_loki-output-sender_loki 
    extract_kubernetes_labels true 
    line_format json 
    remove_keys ["kubernetes"] 
    url "http://loki:3100" 
    <label>
      container $.kubernetes.container_name
      container_id $.kubernetes.docker_id
      host $.kubernetes.host 
      namespace $.kubernetes.namespace_name
      pod $.kubernetes.pod_name
      pod_id $.kubernetes.pod_id 
    </label>
[...]
```
As you can see in the log, testing label is missing

**Additional context**:

**Environment details**:
- Kubernetes version: 1.15.5
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): AWS
- logging-operator version (e.g. 2.1.1): 2.3.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
```
[...]
    @type loki
    @id _loki-flow-monitor_loki-output-sender_loki 
    extract_kubernetes_labels true 
    line_format json 
    remove_keys ["kubernetes"] 
    url "http://loki:3100" 
    <label>
      container $.kubernetes.container_name
      container_id $.kubernetes.docker_id
      host $.kubernetes.host 
      namespace $.kubernetes.namespace_name
      pod $.kubernetes.pod_name
      pod_id $.kubernetes.pod_id 
    </label>
[...]
```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: loki-output-sender
  namespace: monitoring
spec:
  loki:
    url: http://loki:3100
    configure_kubernetes_labels: true
    line_format: json
    extra_labels:
      testing: "testing"
```
/kind bug
