### ISSUE TITLE
Support for fluent-plugin-multi-format-parser

### ISSUE THREAD

**Issue by tesharp** [banzaicloud/logging-operator#244]
**Is your feature request related to a problem? Please describe.**
Need to parse a few log files that uses multiple formats. Would be great if fluent-plugin-multi-format-parser plugin could be supported.

https://github.com/repeatedly/fluent-plugin-multi-format-parser

**Describe the solution you'd like**
Ability to define multi parsers. For instance

```yaml
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        key_name: log
        remove_key_name_field: true
        reserve_data: true
        parsers:
        - type: multi-format
          pattern:
          - format: logfmt
          - format: json
```
