### ISSUE TITLE
Unable to use multiple filters with the same type

### ISSUE THREAD

**Issue by pepov** [banzaicloud/logging-operator#245]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
Cannot configure more than one filter using the same type due to the id's are duplicated.

**Expected behaviour**:
Multiple parser filters chained together should work without issues.

**Steps to reproduce the bug**:
Create a flow with the following configuration:
```
spec:
  filters:
  - tag_normaliser: {}
  - record_transformer:
      records:
      - hostname: '"#{Socket.gethostname}"'
  - parser:
      key_name: log
      parsers:
      - expression: "/^([^ ]+ ){4}(?<original>.*)$/"
        type: regexp
  - parser:
      key_name: original
      type: json
  outputRefs:
  - example
  selectors: {}
```

**Additional context**:
This is on current master.

/kind bug
