### ISSUE TITLE
reload_connections setting is not applied to fluentd

### ISSUE THREAD

**Issue by ziaudin** [banzaicloud/logging-operator#314]
Was struggling with an issue related to fluentd freezing after "failed to flush the buffer" warning in fluentd logs, found a solution described here https://github.com/uken/fluent-plugin-elasticsearch/issues/525#issuecomment-475525764 
But the attempt to change reload_connections to false in my ClusterOutput was not applied to fluentd, sample ClusterOutput:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: cluster-elasticsearch
spec:
  elasticsearch:
    host: logging-cluster-es-http.logging.svc.cluster.local
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    reconnect_on_error: true
    reload_on_failure: true
    reload_connections: false
    buffer:
      timekey: 1m
      timekey_wait: 5s
      timekey_use_utc: true
      chunk_limit_size: 16MB
      flush_mode: interval
      flush_interval: 5s
      flush_thread_count: 8
```
