### ISSUE TITLE
cluster role rules too permisive

### ISSUE THREAD

**Issue by yzargari** [banzaicloud/logging-operator#352]
Looking at https://github.com/banzaicloud/logging-operator/blob/master/docs/deploy/manifests/rbac.yaml - most privileges seem reasonable because they're either limit to reading or limited to non-generic api groups. One exception is the last one, granting '*' on a lot of resources on a lot of generic api groups.

I raised this question in slack and @pepov suggested that it may indeed be overly permissive and that a bug should be reported.

I possibly came up with a list of rules that are narrow enough and still work.

I changed the overly permissive cluster-role rule to just allow get, list and watch and removed the secrets resource from it. I then added a new rule on the secrets resource allowing just list and watch (without reading the content of the secrets).
Finally, I added a role to grant '*' on the entire list of api-groups/resources.

Here's the final list of cluster-role rules:
```
rules:
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - prometheuses/finalizers
  - alertmanagers/finalizers
  - servicemonitors
  - podmonitors
  - prometheusrules
  - podmonitors
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - loggings
  - flows
  - clusterflows
  - outputs
  - clusteroutputs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - logging.banzaicloud.io
  resources:
  - loggings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  - apps
  - batch
  - extensions
  - policy
  - rbac.authorization.k8s.io
  resources:
  - namespaces
  - nodes
  - persistentvolumeclaims
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - endpoints
  - configmaps
  - serviceaccounts
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  - podsecuritypolicies
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
```

Additionally, this is the list of role rules:
```
rules:
- apiGroups:
  - ""
  - apps
  - rbac.authorization.k8s.io
  - extensions
  - policy
  - batch
  resources:
  - replicationcontrollers
  - clusterroles
  - resourcequotas
  - daemonsets
  - serviceaccounts
  - services
  - replicasets
  - rolebindings
  - namespaces
  - podsecuritypolicies
  - jobs
  - roles
  - pods
  - limitranges
  - secrets
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - nodes
  - persistentvolumes
  - clusterrolebindings
  - statefulsets
  - deployments
  verbs:
  - '*'
```

There's possibly more narrowing down that can be done.

I would also add an option to create the cluster role for fluent-bit in advance and only provide the name of it to the logging object, so it doesn't require the write privileges on rbac...

Thanks,
Yosi
