### ISSUE TITLE
Tag normalizer is a fluentd output but a logging-operator filter 

### ISSUE THREAD

**Issue by eddycharly** [banzaicloud/logging-operator#367]
From the fluentd POV, tag_normalizer is an output, but it is a filter from the logging-operator POV.
This is confusing as it will emit events instead letting them flow.

Would it be possible to either make the plugin a filter or change the way it is used in logging-operator so that it is considered an output ?

This is confusing when using a config like this, the event will never be output to s3 because of the grep filter :
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: flow
spec:
  filters:
    - grep:
        regexp:
          - key: $['kubernetes']['namespace_name']['prow.k8s.io/job']
            pattern: /^.+$/
    - dedot: {}
    - tag_normaliser:
        format: ${labels.prow_k8s_io/job}.${labels.prow_k8s_io/build-id}
  outputRefs:
    - s3
  selectors: {}
```
