### ISSUE TITLE
[Question] single_value format with message_key

### ISSUE THREAD

**Issue by eddycharly** [banzaicloud/logging-operator#368]
Is this possible to use the single_value format and specify the message key ?
Thanks

**Comment by tarokkk** [comment]
Can you clarify this for a bit more? An example would be nice as well. Thank you!

**Comment by eddycharly** [comment]
Sure.

I have this kind of output :
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: s3
spec:
  s3:
    instance_profile_credentials: {}
    s3_bucket: xxx
    s3_region: eu-central-1
    path: tekton/${$.job_name}.${$.build_id}/${$.kubernetes.container_name}/
    buffer:
      tags: time,$.job_name,$.build_id,$.kubernetes.container_name
      timekey: 1m
      timekey_wait: 10s
      timekey_use_utc: true
    format:
      type: single_value
```

`single_value` format accepts some parameters see https://docs.fluentd.org/formatter/single_value

Is this possible to pass these parameters to the format ? Something lile this maybe ?
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: s3
spec:
  s3:
    instance_profile_credentials: {}
    s3_bucket: xxx
    s3_region: eu-central-1
    path: tekton/${$.job_name}.${$.build_id}/${$.kubernetes.container_name}/
    buffer:
      tags: time,$.job_name,$.build_id,$.kubernetes.container_name
      timekey: 1m
      timekey_wait: 10s
      timekey_use_utc: true
    format:
      type: single_value
      single_value:
        message_key: log
        add_newline: false
```
