### ISSUE TITLE
extraVolumeMounts not mounting volumes

### ISSUE THREAD

**Issue by amitlt** [banzaicloud/logging-operator#369]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
Volumes specified under `fluentbit.extraVolumeMounts` in a `logging` object do not get mounted.

1. I installed the operator using the the process described in the quickstart [here](https://github.com/banzaicloud/logging-operator/tree/e4d1a625389f91668763d038cd760bc979a01da0/charts/logging-operator#tldr)

2. I created a `Logging` object from the example given [here](https://github.com/banzaicloud/logging-operator/blob/bc7601ddf4679e0df61f1a7189188006304fffbb/docs/crds.md#volume-mount) (except the namespace was `monitoring`)
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-tls
spec:
  fluentd: {}
  fluentbit:
    extraVolumeMounts:
    - source: /opt/docker
      destination: /opt/docker
      readOnly: true
  controlNamespace: monitoring
```

**Expected behaviour**:
A `hostPath` volume to be created and added to every fluentbit pod in the daemonset.

**Steps to reproduce the bug**:
1.  install the operator using the the process described in the quickstart [here](https://github.com/banzaicloud/logging-operator/tree/e4d1a625389f91668763d038cd760bc979a01da0/charts/logging-operator#tldr)

2. create a `Logging` object from the example given [here](https://github.com/banzaicloud/logging-operator/blob/bc7601ddf4679e0df61f1a7189188006304fffbb/docs/crds.md#volume-mount)
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-tls
spec:
  fluentd: {}
  fluentbit:
    extraVolumeMounts:
    - source: /opt/docker
      destination: /opt/docker
      readOnly: true
  controlNamespace: logging
```

3. describe any fluentbit pod for the mounted volumes `kubectl describe pod default-logging-tls-fluentbit-xxxx`

in my case, no extra volume was mounted:
```yaml
Volumes:
  varlibcontainers:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker/containers
    HostPathType:
  varlogs:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-logging-tls-fluentbit
    Optional:    false
  positiondb:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  buffers:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-logging-tls-fluentbit-token-smc5q:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-logging-tls-fluentbit-token-smc5q
    Optional:    false
```
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

**Additional context**:

**Environment details**:
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud-provider/provisioner: kind/minikube (did not work on both)
- logging-operator version: `2.7.0` (what came in the helm values)
- Install method: helm
- Logs from the misbehaving component:
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: provided above

/kind bug
