### ISSUE TITLE
Config checks do not complete, stuck in reconcile loop

### ISSUE THREAD

**Issue by hhtpcd** [banzaicloud/logging-operator#375]
**Describe the bug**:
I am running a Kubernetes cluster that has got 35 Flows, 1 ClusterOutput and there is a ton of churn in configcheck containers completing and starting continuously. ~840 secrets (combination of configcheck and configcheck-output). The logging-operator logs mostly this - 

```
still waiting for the configcheck result...
```

And occasionally - 

```
"msg":"Reconciler error","controller":"logging","request":"/logger","error":"failed to update status: Operation cannot be fulfilled on loggings.logging.banzaicloud.io \"logger\": the object has been modified; please apply your changes to the latest version and try again"
```

It looks to be sticking around here - https://github.com/banzaicloud/logging-operator/blob/205e29f4cafda86323f103ff9ab1cfbd211adca5/pkg/resources/fluentd/fluentd.go#L141 in the reconcile loop, perhaps unable to identify the status of the configcheck result.

I'm not getting any logs out to the ClusterOutput and there appears to be no end in sight for the looping configcheck containers. Have followed the troubleshooting steps and raised on Slack and was asked to file an issue.

**Expected behaviour**:
The configcheck containers complete either fail/succeed, clean up after themselves and there are not hundreds of secrets and jobs continuously being created.

**Steps to reproduce the bug**:
Create 35 Flows in the cluster. All Flows are essentially the same, with different selectors.

```yaml
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.namespace}}
spec:
  controlNamespace: monitoring
  filters:
    - detectExceptions:
        multiline_flush_interval: "0.1"
        languages:
          - java
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: json
  selectors:
    service-name: {{.Chart.Name}}
  outputRefs:
    - cluster-elastic
```

**Additional context**:
We are currently running the logging-operator with ` flowConfigCheckDisable: true` which we would really rather not do, as it's increased the feedback loop for new Flows. 

Incidentally if you have any thoughts on ways to test Flow configuration before it gets to the cluster, that would be great too :)

**Environment details**:
- Kubernetes version: 1.14.8
- Cloud-provider/provisioner: GKE
- logging-operator version (e.g. 2.1.1): 2.7.1-rc.1
- Install method (e.g. helm or static manifests): Helm chart v2.7.1

/kind bug
