### ISSUE TITLE
Kinesis stream doesn't generate assume_role configuration

### ISSUE THREAD

**Issue by empath-75** [banzaicloud/logging-operator#378]
**Describe the bug**:
If you include a section like the following in your config:
```
apiVersion: logging.banzaicloud.io/v1beta1
  kind: ClusterOutput
  metadata:
    name: kinesis-output-cluster
    namespace: logging-operator
  spec:
    kinesisStream:
      assume_role_credentials:
        role_arn: arn:aws:iam::1111/IAM_ROLE_NAME
        role_session_name: logging-operator
      buffer:
        timekey: 30s
        timekey_use_utc: true
        timekey_wait: 30s
      region: us-east-1
      stream_name: foo
```

it generates a config like this:

 ```
<match **>
    @type kinesis_streams
    @id logging-operator_nginx-flow-cluster_kinesis-output-cluster_kinesis_streams
    region us-east-1
    stream_name foo
    <buffer tag,time>
      @type file
      path /buffers/logging-operator_nginx-flow-cluster_kinesis-output-cluster_kinesis_streams.*.buffer
      retry_forever true
      timekey 30s
      timekey_use_utc true
      timekey_wait 30s
    </buffer>
  </match>
```

**Expected behaviour**:
A concise description of what you expected to happen.

The generated config should look like:

 ```
<match **>
    @type kinesis_streams
    @id logging-operator_nginx-flow-cluster_kinesis-output-cluster_kinesis_streams
    region us-east-1
    stream_name foo
    <assume_role_credentials>
        role_arn          arn:aws:iam::1111/IAM_ROLE_NAME
        role_session_name logging-operator
      </assume_role_credentials>
    <buffer tag,time>
      @type file
      path /buffers/logging-operator_nginx-flow-cluster_kinesis-output-cluster_kinesis_streams.*.buffer
      retry_forever true
      timekey 30s
      timekey_use_utc true
      timekey_wait 30s
    </buffer>
  </match>
```

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.15.3
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
- logging-operator version (e.g. 2.1.1): 3.0.0-rc1
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
