### ISSUE TITLE
Allow additional configuration options for filters

### ISSUE THREAD

**Issue by pehlert** [banzaicloud/logging-operator#392]
logging-operator allows to use e.g. `multiline` as a parser filter type in its flow declaration.
However (unless I got something wrong while browsing through the source code and trying to analyze this issue) it ignores any additional parameters then, so the following configuration will fail the config check because `format_firstline` and `format1` never make it to the actual config:

```
spec:
  filters:
  - parser:
      parse:
        format_firstline: /^(.*?)\[(.*?)\]\s(?<loglevel>.*?):/
        format1: /^(.*?)\[(.*?)\]\s(.*?):(?<msg>.*)/
        type: multiline
```

I would appreciate if someone from the core team could confirm the behaviour. I think this could almost be considered a bug because the documented and valid option `multiline` will never work without additional configuration.
