### ISSUE TITLE
ClusterOutput Loki - buffer retry_forever parameter ignored

### ISSUE THREAD

**Issue by StefanCenusa** [banzaicloud/logging-operator#400]
**Describe the bug**:
According to the [docs](https://github.com/banzaicloud/logging-operator/blob/master/docs/plugins/outputs/buffer.md) for the Loki output the retry_forever parameter should be available to be set to false. When applied, the parameter is ignored and the fluentd config sets it as true.

**Expected behaviour**:
retry_forever to be false

**Steps to reproduce the bug**:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: loki-output
  namespace: logging
spec:
  loki:
    url: <loki_url>
    configure_kubernetes_labels: true
    buffer:
      retry_forever: false
      retry_max_times: 2
  loggingRef: core-logging
```
After applying it to the cluster, tail logs on the configcheck pod:
`kubectl logs core-logging-fluentd-configcheck-58cada83`

```
<match **>
      @type loki
      @id logging_core-logging_core-output_loki
      extract_kubernetes_labels true
      line_format json
      remove_keys ["kubernetes"]
      url "<loki_url>
      <label>
        container $.kubernetes.container_name
        container_id $.kubernetes.docker_id
        host $.kubernetes.host
        namespace $.kubernetes.namespace_name
        pod $.kubernetes.pod_name
        pod_id $.kubernetes.pod_id
      </label>
      <buffer tag,time>
        @type "file"
        ....
        retry_forever true
        retry_max_times 2
       ....
      </buffer>
    </match>
```

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v.1.16
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): on-premise
- logging-operator version (e.g. 2.1.1): 3
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
