### ISSUE TITLE
Add in helm chart and operator code supporting of priorityClassName

### ISSUE THREAD

**Issue by evilrussian** [banzaicloud/logging-operator#422]
**Is your feature request related to a problem? Please describe.**
Helm chart doesn't support priorityClassName for logging operator deployment
Operator doesn't support priorityClassName for created by it StatefulSet's and Daemonset's.
If we will have any resources pressure at nodes, kubernetes can evict logging pods before evict any application ( because by default whey all have priority 0 ). And we can lost logs ( kubernetes doesn't restart daemonset's after evicting) 

**Describe the solution you'd like**
1) Helm chart must support of priorityClassName for logging operator deployment. It's very easy.
In templates/deployment.yaml add this:
```
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
{{- end }}
```
In values.yaml:
```
priorityClassName: {}
```

2) Operator must support of priorityClassName for created by it pods. For example,
For example, it can be new custom field priorityClassName
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-simple
  namespace: logging
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: logging
  priorityClassName: cluster-observability-pods
```
and logging operator must create fluentd's sts and fluentbit's daemonset with priorityClassName `cluster-observability-pods`

It all can prevent lost of logs
