### ISSUE TITLE
Configure default_route option from fluent-plugin-label-router

### ISSUE THREAD

**Issue by PhilGrayson** [banzaicloud/logging-operator#423]
**Is your feature request related to a problem? Please describe.**
I'd like to define a Flow to catch all logs that have not matched any other Flow or ClusterFlow. This is so every stdout line from containers can be handled without duplication.

Specifically, I'm working on a multi-tenant Kubernetes cluster and want to provide an Elasticsearch index of unhandled logs. If a team wishes for their logs to be handled differently (for example the logs contain sensitive data and need more restrictive access control) the team can define a Flow and Output object in their own namespace.

I could define a ClusterFlow without any `match` arguments. However that ClusterFlow also matches logs that have already been matched by other Flow and ClusterFlows.

**Describe the solution you'd like**
There are of options I can imagine. Either:
Expose a DefaultClusterFlow field on the LoggingSpec.
OR
Expose a DefaultClusterFlow type. Only one instance of DefaultClusterFlow is allowed per Logging instance. The DefaultClusterFlowSpec looks like a ClusterFlowSpec but it doesn't contain a Match or Selectors field.

**Pros of the new field**
Doesn't introduce another Flow variant object.
More intuitive at-most-one definition of a default flow. A user can either set the field or not, they cannot accidentally define more than one default flows.

**Cons of the new field**
The referenced ClusterFlow has two purposes now. One to process logs according to some Match or Selectors and one to process logs that didn't match any other ClusterFlow/Flow. This can be non-intuitive. Furthermore, the Logging object has a weak reference to the ClusterFlow name. If the ClusterFlow object is deleted or renamed, the reference would still exist.

**Pros of the new type**
This Flow type has a clear purpose since it doesn't have a Match or Selectors field. 

**Cons of the new type**
Yet another Flow variant, I still wonder if this confusing to users.

**Comment by pepov** [comment]
I think this is reasonable and great job on the implementation! I would personally opt for exposing this in the LoggingSpec but without actually creating a clusterflow object in the background. Let us think this through and come back to you with a preferred solution.

**Comment by PhilGrayson** [comment]
That sounds like a good idea, something like:

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default
spec:
  [...]
  defaultFlow:
    filters:
      - dedot:
          de_dot_nested: true
          de_dot_separator: '-'
      - detectExceptions:
          multiline_flush_interval: 1s
    outputRefs:
      - my-output
```

Naming wise, it's important to be precise about this flow's purpose. I thought of names like fallthroughFlow, unmatchedLogFlow. Just throwing ideas out there.
