### ISSUE TITLE
Validating admission webhook for Flows and Outputs

### ISSUE THREAD

**Issue by PhilGrayson** [banzaicloud/logging-operator#429]
## Description of the issue

It is easy to configure Flow and Outputs that result in breaking the reconciliation of the associated Logging object. Users have no idea if their Flows and Outputs are valid unless they know to check the Logging Operator logs. 

#### Example one
```
cat <<EOF | kubectl -n logging apply -f -
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: shared
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: logging
EOF

cat <<EOF | kubectl -n logging apply -f -
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: null-output
spec:
  nullout: {}
EOF

cat <<EOF | kubectl -n logging apply -f -
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow
spec:
  outputRefs:
    # oops, got the wrong Output name
    - null-out
EOF
```
In this example the reconcile loop errors with:

> failed to create model: referenced output not found: null-out"

#### Example two
```
cat <<EOF | kubectl -n logging apply -f -
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: shared
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: logging
EOF

cat <<EOF | kubectl -n logging apply -f -
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: null-output
spec:
  nullout: {}
EOF

cat <<EOF | kubectl -n logging apply -f -
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow
spec:
  filters:
    # Here, `parse` should be `parser`. This is documented incorrectly in
    # example from https://github.com/banzaicloud/logging-operator/blob/272fc063/docs/plugins/filters/parser.md#example-parser-filter-configurations
    - parse:
        parse:
          type: apache2
  outputRefs:
    - null-output
EOF
```
In this example the reconcile loop errors with:
> failed to create model: failed to create filter with index 0 for flow flow: no plugin config available for filter

#### Example three
```
cat <<EOF | kubectl -n logging apply -f -
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: shared
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: logging
EOF

cat <<EOF | kubectl -n logging apply -f -
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: file-output-1
spec:
  file:
    path: /tmp/log/fluentd
EOF

cat <<EOF | kubectl -n logging apply -f -
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: file-output-2
spec:
  file:
    path: /tmp/log/fluentd
EOF

cat <<EOF | kubectl -n logging apply -f -
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow
spec:
  outputRefs:
    - file-output-1
    - file-output-2
EOF
```
In this example the reconcile loop errors with:

>current config is invalid

Looking at the configcheck pod logs shows the config error.

>[error]: config error file="/fluentd/etc/generated.conf" error_class=Fluent::ConfigError error="Other 'file' plugin already use same buffer path: type = file, buffer path = /tmp/log/fluentd"

## Possible solutions

 It would be great if the Flow and Output objects are checked via a validating admission webhook. That would make configuration errors more visible to the end-user and prevent breaking the reconcile loop for the Logging object.

I imagine the first two examples could be covered fairly easily.

Handling fluentd config errors as early as possible would be really useful too. The webhook could reuse the existing [configCheck()](https://github.com/banzaicloud/logging-operator/blob/272fc0639d611f28eaea9364346775d56e5d932b/pkg/resources/fluentd/appconfigmap.go#L58) functionality. However, this could be more flakey due to the [30 second execution limitation](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#timeouts). Pods can take an undefined amount of time to schedule. There is a possible workaround, attach a fluentd sidecar to the logging operator and execute the `fluentd -c` command in that container instead of creating a new pod. Although that does mean the secret handling wouldn't work.
