### ISSUE TITLE
NewRelic plugin pushes same logs to NewRelic logs

### ISSUE THREAD

**Issue by joosangkim** [banzaicloud/logging-operator#431]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
NewRelic output plugin generate duplicated logs on NewRelic Logs.

**Expected behaviour**:
NewRelic output plugin for logging-operator should push same log at once to NewRelic Logs.

**Steps to reproduce the bug**:
I generated logging-operator ClusterFlow and ClusterOutput for NewRelic Logs on EKS. When I checked NewRelic Logs there were multiple duplicated logs. 
<img width="1460" alt="스크린샷 2020-04-02 오후 7 44 38" src="https://user-images.githubusercontent.com/49609358/78241304-21cef700-751b-11ea-9637-feb5881c83b3.png">

Duplicated logs has same timestamp and generated from same pod and container, but fluentd generated by logging-operator shoots same logs multiple time.

Below is `stdout` log from fluentd generated by logging-operator. 
`2020-04-02 05:23:37.086127062 +0000 normalized.tag.for.eks: {"stream":"stdout","time":"2020-04-02T05:23:36.027575785Z","kubernetes":{"pod_name":"pod-name-hash","namespace_name":"default","pod_id":"7bbffc22-749c-11ea-bbd8-0680ce3b4b02","host":"eks.host.interal","container_name":"custom.container.name","docker_id":"0dc4b857f8093967b02a37c4be9614c4eab7cf484e98e0f196d572ed0797b283","container_hash":"2bc8f13afc879feffccfe409924976100742a4f7dd81d127b71e1a0d9e1043f5"},"level":"DEBUG","ts":"2020-04-02T05:23:36.027Z","caller":"fetchemit/fetch_emit_tail.go:106","msg":"no more task","networkId":8217}
2020-04-02 05:23:37.086587477 +0000 normalized.tag.for.eks: {"stream":"stdout","time":"2020-04-02T05:23:36.027575785Z","kubernetes":{"pod_name":"pod-name-hash","namespace_name":"default","pod_id":"7bbffc22-749c-11ea-bbd8-0680ce3b4b02","host":"eks.host.interal","container_name":"custom.container.name","docker_id":"0dc4b857f8093967b02a37c4be9614c4eab7cf484e98e0f196d572ed0797b283","container_hash":"2bc8f13afc879feffccfe409924976100742a4f7dd81d127b71e1a0d9e1043f5"},"level":"DEBUG","ts":"2020-04-02T05:23:36.027Z","caller":"fetchemit/fetch_emit_tail.go:106","msg":"no more task","networkId":8217}
2020-04-02 05:23:37.087021670 +0000 normalized.tag.for.eks: {"stream":"stdout","time":"2020-04-02T05:23:36.027575785Z","kubernetes":{"pod_name":"pod-name-hash","namespace_name":"default","pod_id":"7bbffc22-749c-11ea-bbd8-0680ce3b4b02","host":"eks.host.interal","container_name":"custom.container.name","docker_id":"0dc4b857f8093967b02a37c4be9614c4eab7cf484e98e0f196d572ed0797b283","container_hash":"2bc8f13afc879feffccfe409924976100742a4f7dd81d127b71e1a0d9e1043f5"},"level":"DEBUG","ts":"2020-04-02T05:23:36.027Z","caller":"fetchemit/fetch_emit_tail.go:106","msg":"no more task","networkId":8217}
2020-04-02 05:23:37.087443057 +0000 normalized.tag.for.eks: {"stream":"stdout","time":"2020-04-02T05:23:36.027575785Z","kubernetes":{"pod_name":"pod-name-hash","namespace_name":"default","pod_id":"7bbffc22-749c-11ea-bbd8-0680ce3b4b02","host":"eks.host.interal","container_name":"custom.container.name","docker_id":"0dc4b857f8093967b02a37c4be9614c4eab7cf484e98e0f196d572ed0797b283","container_hash":"2bc8f13afc879feffccfe409924976100742a4f7dd81d127b71e1a0d9e1043f5"},"level":"DEBUG","ts":"2020-04-02T05:23:36.027Z","caller":"fetchemit/fetch_emit_tail.go:106","msg":"no more task","networkId":8217}
2020-04-02 05:23:37.087867834 +0000 normalized.tag.for.eks: {"stream":"stdout","time":"2020-04-02T05:23:36.027575785Z","kubernetes":{"pod_name":"pod-name-hash","namespace_name":"default","pod_id":"7bbffc22-749c-11ea-bbd8-0680ce3b4b02","host":"eks.host.interal","container_name":"custom.container.name","docker_id":"0dc4b857f8093967b02a37c4be9614c4eab7cf484e98e0f196d572ed0797b283","container_hash":"2bc8f13afc879feffccfe409924976100742a4f7dd81d127b71e1a0d9e1043f5"},"level":"DEBUG","ts":"2020-04-02T05:23:36.027Z","caller":"fetchemit/fetch_emit_tail.go:106","msg":"no more task","networkId":8217}
2020-04-02 05:23:37.088297729 +0000 normalized.tag.for.eks: {"stream":"stdout","time":"2020-04-02T05:23:36.027575785Z","kubernetes":{"pod_name":"pod-name-hash","namespace_name":"default","pod_id":"7bbffc22-749c-11ea-bbd8-0680ce3b4b02","host":"eks.host.interal","container_name":"custom.container.name","docker_id":"0dc4b857f8093967b02a37c4be9614c4eab7cf484e98e0f196d572ed0797b283","container_hash":"2bc8f13afc879feffccfe409924976100742a4f7dd81d127b71e1a0d9e1043f5"},"level":"DEBUG","ts":"2020-04-02T05:23:36.027Z","caller":"fetchemit/fetch_emit_tail.go:106","msg":"no more task","networkId":8217}
2020-04-02 05:23:37.088717113 +0000 normalized.tag.for.eks: {"stream":"stdout","time":"2020-04-02T05:23:36.027575785Z","kubernetes":{"pod_name":"pod-name-hash","namespace_name":"default","pod_id":"7bbffc22-749c-11ea-bbd8-0680ce3b4b02","host":"eks.host.interal","container_name":"custom.container.name","docker_id":"0dc4b857f8093967b02a37c4be9614c4eab7cf484e98e0f196d572ed0797b283","container_hash":"2bc8f13afc879feffccfe409924976100742a4f7dd81d127b71e1a0d9e1043f5"},"level":"DEBUG","ts":"2020-04-02T05:23:36.027Z","caller":"fetchemit/fetch_emit_tail.go:106","msg":"no more task","networkId":8217}
2020-04-02 05:23:37.089138819 +0000 normalized.tag.for.eks: {"stream":"stdout","time":"2020-04-02T05:23:36.027575785Z","kubernetes":{"pod_name":"pod-name-hash","namespace_name":"default","pod_id":"7bbffc22-749c-11ea-bbd8-0680ce3b4b02","host":"eks.host.interal","container_name":"custom.container.name","docker_id":"0dc4b857f8093967b02a37c4be9614c4eab7cf484e98e0f196d572ed0797b283","container_hash":"2bc8f13afc879feffccfe409924976100742a4f7dd81d127b71e1a0d9e1043f5"},"level":"DEBUG","ts":"2020-04-02T05:23:36.027Z","caller":"fetchemit/fetch_emit_tail.go:106","msg":"no more task","networkId":8217}`

I declared newrelic logs clusteroutput and s3 clusteroutput. 

**Additional context**:
***ClusterFlow***
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: {{ .Release.Name }}-clusterflow-all
  namespace: {{ .Release.Namespace }}
spec:
  filters:
    - grep: 
        exclude:
          - key: $.kubernetes.container_name
            pattern: /^audit\-log$/
    - tag_normaliser:
        format: ${namespace_name}.${pod_name}.${container_name}
    - parser:
        key_name: log
        reserve_data: true 
        remove_key_name_field: true
        parse: 
          type: json  
    - record_transformer: # newrelic put 'plugin'tag
        remove_keys: "stream,C,caller,S,node"
    - stdout:
       output_type: json
  match:
    - exclude:
        namespaces: [kube-system,monitoring,default]
    - select: {}
  outputRefs:
    - {{ .Release.Name }}-clusteroutput-all-newrelic
    - {{ .Release.Name }}-clusteroutput-all-s3
```
***ClusterOutput(NewRelic)***
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: {{ .Release.Name }}-clusteroutput-all-newrelic
  namespace: {{ .Release.Namespace }}
spec:
  newrelic:
    license_key:
      valueFrom:
        secretKeyRef:
          name: logging-newrelic
          key: nr_license
```
***ClusterOutput(S3)***
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: {{ .Release.Name }}-clusteroutput-all-s3
  namespace: {{ .Release.Namespace }}
spec:
  s3:
    s3_bucket: {{ .Values.output.catchallS3.bucket }}
    s3_region: {{ .Values.output.catchallS3.region }}
    instance_profile_credentials: {}
    path: {{ .Values.output.catchallS3.prefix }}/${tag}/%Y/%m/%d/
    buffer:
      timekey: 1h
      timekey_wait: 5m
      timekey_use_utc: true
      chunk_limit_size: 64MB
    format:
      type: json
```
**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.14.8-eks-b8860f
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): helm chart: logging-operator-3.0.3  
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
