### ISSUE TITLE
Support Datadog plugin in (cluster) output

### ISSUE THREAD

**Issue by ncrothe** [banzaicloud/logging-operator#477]
**Is your feature request related to a problem? Please describe.**
We use Datadog as final destination for our log events. Right now this means we need to maintain a second, external Fluentd installation that we forward to from the logging-operator-managed one.

**Describe the solution you'd like**
Support the Fluentd Datadog Plugin in the output and clusteroutput resources.

**Describe alternatives you've considered**
Alternatively, open up output resources for generic plugins - as long as the container image has them installed which could be done by users maintaining an appropriate downstream image.

**Additional context**
Fluentd Datadog plugin docs at https://www.rubydoc.info/gems/fluent-plugin-datadog

**Comment by ncrothe** [comment]
I was able to circumvent the missing Datadog plugin by using the out_http plugin and configuring that with the necessary details. Sample snippet below:

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: datadog
spec:
  http:
    content_type: "application/json"
    endpoint: https://http-intake.logs.datadoghq.com/v1/input
    headers:
      DD-API-KEY: MY_DATADOG_KEY
    buffers:
      chunk_limit_size: 5MB
      compress: gzip
      flush_mode: interval
      flush_interval: 10s
```
