### ISSUE TITLE
Fluentd goes down if ES output host doesn't exists

### ISSUE THREAD

**Issue by overdrive3000** [banzaicloud/logging-operator#491]
**Describe the bug**:
If an `output` type `elasticsearch` is misconfigured with a wrong host will make `fluentd` application to stop listening in port 24240, by hence `fluentbit` won't be able to forward logs to `fluentd`.

```
[2020/05/26 13:11:55] [error] [output:forward:forward.0] no upstream connections available
[2020/05/26 13:11:55] [ warn] [engine] failed to flush chunk '1-1590497162.576911910.flb', retry in 1927 seconds: task_id=437, input=tail.0 > output=forward.0
[2020/05/26 13:11:58] [error] [io] TCP connection failed: main-logging-fluentd.logging.svc:24240 (Connection refused)
[2020/05/26 13:11:58] [error] [output:forward:forward.0] no upstream connections available
[2020/05/26 13:11:58] [ warn] [engine] failed to flush chunk '1-1590497198.578125692.flb', retry in 1900 seconds: task_id=477, input=tail.0 > output=forward.0
```

Below the output of the `netstat -napt` command when this happen:

```
/fluentd/app-config $ netstat -antp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name   
tcp        0      0 127.0.0.1:24444         0.0.0.0:*               LISTEN      6/ruby
```

Some logs from `fluentd`:

```
2020-05-26 12:39:43 +0000 [warn]: #0 [flow:xxxxx:output:xxxxx:yyyyy] Could not communicate to Elasticsearch, resetting connection and trying again. getaddrinfo: Name does not resolve (SocketError)
2020-05-26 12:39:43 +0000 [warn]: #0 [flow:xxxxx:output:xxxxx:yyyyy] Remaining retry: 13. Retry to communicate after 4 second(s).
2020-05-26 12:39:51 +0000 [warn]: #0 [flow:xxxxx:output:xxxxx:yyyyy] Could not communicate to Elasticsearch, resetting connection and trying again. getaddrinfo: Name does not resolve (SocketError)
```

Kubernetes services in logging namespace:

```
$ kubectl get svc -n logging
NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)               AGE
elasticsearch-master             ClusterIP   172.20.97.1     <none>        9200/TCP,9300/TCP     4d21h
elasticsearch-master-headless    ClusterIP   None            <none>        9200/TCP,9300/TCP     4d21h
kibana-kibana                    ClusterIP   172.20.69.189   <none>        5601/TCP              4d21h
logging-operator                 ClusterIP   172.20.12.107   <none>        8080/TCP              4d4h
main-logging-fluentbit-monitor   ClusterIP   None            <none>        2020/TCP              4d4h
main-logging-fluentd             ClusterIP   172.20.179.8    <none>        24240/TCP,24240/UDP   4d4h
main-logging-fluentd-metrics     ClusterIP   None            <none>        24231/TCP             4d4h
```

The real problem here is that it will make all log streaming configuration to fail even the ones using other output types as the whole fluentd stop listening. Beisde of that fixing the `output` type with the right hostname won't fix the issue as `fluentd` seems unable to reload the new configuration. 

**Expected behaviour**:
I'd expect `fluentd`  failing to send logs to the misconfigured Elasticsearch (output) but keep `fluentd` working for the other log configuration routes.

I think this is most likely a problem of fluentd and not properly of the logging-operator but it would be great to catch this configuration issue in "configcheck time" and not to render the output configuration if Elasticsearch host doesn't exists this way at least there whole logging system won't be impacted.

**Steps to reproduce the bug**:
This can be easily reproduced by using an standard logging-operator configuration (installed via Helm) and a `Flow` and `Output` like the following one:

```
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: my-app-es
  namespace: app
spec:
  elasticsearch:
    host: fake.logging.svc.cluster.local
    port: 9200
    scheme: http
    logstash_format: true
    logstash_prefix: my-app
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
      overflow_action: drop_oldest_chunk
      queued_chunks_limit_size: 3600
      retry_forever: false

---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: my-app
  namespace: app
spec:
  filters:
    - tag_normaliser:
        format: cluster.${namespace_name}.${pod_name}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: json
  selectors:
    name: my-app
  outputRefs:
    - my-app-es
```

**Additional context**:
I am using `elasticsearch` and `newrelic` output, so far this problem is triggered when elasticsearch host doesn't exists, for example using a wrong API Key for New Relic will fail to stream logs to New Relic logs but the whole system keep working as expected.

**Environment details**:
- Kubernetes version : v1.14.9-eks-f459c0
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): 3.2.0
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs): Some log output is shown in the bug description
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: See an example above.

/kind bug
