### ISSUE TITLE
Flow match configurations

### ISSUE THREAD

**Issue by bygui86** [banzaicloud/logging-operator#509]
**Describe the bug**:
Configuring a Flow with `match.exclude` to get logs only from services excluding databases, does not work as expected.

**Expected behaviour**:
I tried this Flow:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: gcs-flow
  namespace: example
spec:
  match:
    - exclude:
        labels:
          group: databases
  filters:
    - tag_normaliser:
        format: ${namespace_name}/${labels.app}/${container_name}
    - parser:
        key_name: message
        reserve_time: true
        reserve_data: true
        remove_key_name_field: true
        inject_key_prefix: log_
        parse:
          type: json
          keep_time_key: true
          utc: true
  outputRefs:
    - gcs-cluster-output
```
together with this ClusterOutput:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: gcs-cluster-output
  namespace: logging
spec:
  gcs:
    credentials_json:
      valueFrom:
        secretKeyRef:
          name: ***
          key: ***
    client_retries: 10
    client_timeout: 5
    project: ***
    bucket: ***
    auto_create_bucket: true
    path: ${tag}/%Y-%m-%d_%H/
    store_as: text
    buffer:
      timekey: 5m
      timekey_wait: 10s
      timekey_use_utc: true
      chunk_limit_size: 5MB
      flush_at_shutdown: true
      flush_mode: interval
      flush_interval: 30s
      retry_forever: false
      retry_max_times: 50
```
and I was expecting to see in Google Cloud Storage (GCS) logs of **all services except databases**, but actually I saw **no logs** and I don't see any error in logging-operator or Fluentd logs.

Changing Flow definition adding `match.select` section, everything works as expected:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: gcs-flow
  namespace: example
spec:
  match:
    - select:
        labels:
          group: services
    - exclude:
        labels:
          group: databases
  filters:
    - tag_normaliser:
        format: ${namespace_name}/${labels.app}/${container_name}
    - parser:
        key_name: message
        reserve_time: true
        reserve_data: true
        remove_key_name_field: true
        inject_key_prefix: log_
        parse:
          type: json
          keep_time_key: true
          utc: true
  outputRefs:
    - gcs-cluster-output
```

**Steps to reproduce the bug**:
1. Deploy logging-operator following official quickstart guide
2. Deploy ClusterOutput and Flow
3. Deploy Logging
4. Wait for 5 min to see logs in GCS

**Additional context**:
Nothing

**Environment details**:
- Kubernetes version: 1.15.9-gke.24
- Cloud-provider/provisioner: GKE
- logging-operator version: 3.1.2
- Install method: static manifests
- Logs from the misbehaving component (and any other relevant logs):
  - logging-operator logs are normal without errors
  - Fluentd has literally no logs
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: see the above bug description and additionally Logging following
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-components
  namespace: logging
spec:
  enableRecreateWorkloadOnImmutableFieldChange: true
  controlNamespace: logging
  fluentbit:
    metrics:
      serviceMonitor: true
    tolerations:
      - effect: NoSchedule
        operator: Exists
        key: node-role.kubernetes.io/master
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
  fluentd:
    logLevel: debug
    metrics:
      serviceMonitor: true
    tolerations:
      - key: dedicated
        operator: Equal
        value: logging
        effect: NoSchedule
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                    - logging
```

I read in the documentation [here](https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/flow_types/) and it's not specified that `select` and `exclude` are mutual exclusive or must be used together.

/kind bug
