### ISSUE TITLE
seLinuxOptions is not supported

### ISSUE THREAD

**Issue by kenankule** [banzaicloud/logging-operator#514]
**Describe the bug**:
seLinuxOptions, a property of the securityContext, is not supported / used in the created statefulset and daemonset template although it was mentioned in the spec documentation. We'd like to use the SELinux type `container_logreader_t` in the fluent bit pods.

**Expected behaviour**:
seLinuxOptions (e.g. `type: "container_logreader_t"` ) passed as Security variables to the Fluentbit and Fluentd specs should be used in the daemonset and statefulset definition

**Steps to reproduce the bug**:
Create a logging resource using the following definition:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: simple
  namespace: ocp-logging
spec:
  fluentd:
    tls:
      enabled: true
      secretName: fluentd-tls
      sharedKey: qwerasdf
  fluentbit:
    image:
      repository: fluent/fluent-bit
      tag: 1.4.6-debug
    tls:
      enabled: true
      secretName: fluentbit-tls
      sharedKey: qwerasdf
    security:
      securityContext:
        seLinuxOptions:
          type: "container_logreader_t"
  controlNamespace: ocp-logging
```
The securityContext of the daemonset and statefulset is empty:
```
➜ oc get ds simple-fluentbit -o yaml | grep securityContext
        securityContext: {}
      securityContext: {}
```

**Additional context**:
Looking at the following code pieces i cannot see seLinuxOptions being used. 

Statefulset:
https://github.com/banzaicloud/logging-operator/blob/464fe9d03f19ec3b9bf6aacacdd065246fff1d06/pkg/resources/fluentd/statefulset.go#L95 

Daemonset
https://github.com/banzaicloud/logging-operator/blob/464fe9d03f19ec3b9bf6aacacdd065246fff1d06/pkg/resources/fluentbit/daemonset.go#L74

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v.1.17.1
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Openshift onprem
- logging-operator version (e.g. 2.1.1): 3.3.0
- Install method (e.g. helm or static manifests): manifests
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
