### ISSUE TITLE
logging-operator-logging-fluentd.logging.svc:24240 (Connection timed out)

### ISSUE THREAD

**Issue by acarsercan** [banzaicloud/logging-operator#551]
Hi,

I'm trying to setup logging solution using the logging-operator. Combining fluent-bit, fluentd, S3, loki and grafana

I'm running kubernetes 1.15.9

```
helm install --namespace logging --name logging banzaicloud-stable/logging-operator
```

```
helm install --name loki loki/loki -f loki.yaml --namespace logging

values

config:
  schema_config:
    configs:
    - from: 2020-05-15
      store: aws
      object_store: s3
      schema: v11
      index:
        prefix: loki_index
        period: 336h
  storage_config:
    aws:
      s3: s3://XXXX
      bucketnames: ccuk-kubernetes-loki
      dynamodb:
        dynamodb_url: dynamodb://XXXXX
  table_manager:
    retention_deletes_enabled: true
    retention_period: 336h
```
Clusterflow
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: clusterflow-sample
spec:
  outputRefs:
    - loki-output
  match:
    - select:
        namespaces:
          - production-dynamo
```

output
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
 name: loki-output
spec:
 loki:
   url: http://loki:3100
   configure_kubernetes_labels: true
   buffer:
     timekey: 1m
     timekey_wait: 30s
     timekey_use_utc: true
```

Logging
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-operator-logging
spec:
  fluentd:
    logLevel: debug
    fluentOutLogrotate:
      enabled: true
      path: /fluentd/log/out
      age: "10"
      size: "10485760"
    scaling:
      replicas: 3
  fluentbit:
    inputTail:
      Mem_Buf_Limit: "256MB"
    filterKubernetes:
       Kube_URL: "https://kubernetes.default.svc:443"
       Match: "kube.*"
  controlNamespace: logging
```

k8s svc in logging namespace
```

NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)               AGE
logging-logging-operator           ClusterIP   None             <none>        8080/TCP              22h
logging-operator-logging-fluentd   ClusterIP   100.69.2.88      <none>        24240/TCP,24240/UDP   5m36s
loki                               ClusterIP   100.70.252.253   <none>        3100/TCP              21h
loki-headless                      ClusterIP   None             <none>        3100/TCP              21h
```

I was hoping to see logs from production-dynamo namespace, however I don't. Here is the error which I'm failing to solve
```
logging/logging-operator-logging-fluentbit-drntr[fluent-bit]: [2020/08/11 13:29:47] [error] [output:forward:forward.0] no upstream connections available
logging/logging-operator-logging-fluentbit-drntr[fluent-bit]: [2020/08/11 13:29:47] [error] [io] TCP connection failed: logging-operator-logging-fluentd.logging.svc:24240 (Connection timed out)
logging/logging-operator-logging-fluentbit-drntr[fluent-bit]: [2020/08/11 13:29:47] [error] [output:forward:forward.0] no upstream connections available
logging/logging-operator-logging-fluentbit-drntr[fluent-bit]: [2020/08/11 13:29:47] [error] [io] TCP connection failed: logging-operator-logging-fluentd.logging.svc:24240 (Connection timed out)
logging/logging-operator-logging-fluentbit-drntr[fluent-bit]: [2020/08/11 13:29:47] [error] [output:forward:forward.0] no upstream connections available
logging/logging-operator-logging-fluentbit-drntr[fluent-bit]: [2020/08/11 13:29:47] [error] [io] TCP connection failed: logging-operator-logging-fluentd.logging.svc:24240 (Connection timed out)
logging/logging-operator-logging-fluentbit-drntr[fluent-bit]: [2020/08/11 13:29:47] [error] [output:forward:forward.0] no upstream connections available
logging/logging-operator-logging-fluentbit-drntr[fluent-bit]: [2020/08/11 13:29:47] [error] [io] TCP connection failed: logging-operator-logging-fluentd.logging.svc:24240 (Connection timed out)
logging/logging-operator-logging-fluentbit-drntr[fluent-bit]: [2020/08/11 13:29:47] [error] [output:forward:forward.0] no upstream connections available
```

Replies are appreciated

Regards
