### ISSUE TITLE
kafka output error - undefined method call for Kafka::Partitioner:Class

### ISSUE THREAD

**Issue by jdonnelly-apixio** [banzaicloud/logging-operator#559]
**Describe the bug**:
I get an exception when sending parser:none logs to kafka. It looks like we might need to upgrade the kafka plugin to 0.14.1.

The error from /fluentd/log/out:
```
2020-08-20 23:20:44 +0000 [debug]: #0 [clusterflow:logging:kafka-flow:clusteroutput:logging:kafka-cluster-output] 511961 messages send.
2020-08-20 23:20:44 +0000 [warn]: #0 [clusterflow:logging:kafka-flow:clusteroutput:logging:kafka-cluster-output] Send exception occurred: undefined method `call' for Kafka::Partitioner:Class
2020-08-20 23:20:44 +0000 [warn]: #0 [clusterflow:logging:kafka-flow:clusteroutput:logging:kafka-cluster-output] Exception Backtrace : /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:253:in `block in assign_partitions!'
/usr/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.2.0/lib/kafka/pending_message_queue.rb:38:in `each'
/usr/lib/ruby/gems/2.7.0/gems/ruby-kafka-1.2.0/lib/kafka/pending_message_queue.rb:38:in `each'
/usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:248:in `assign_partitions!'
/usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:209:in `block in deliver_messages_with_retries'
/usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:200:in `loop'
/usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:200:in `deliver_messages_with_retries'
/usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/kafka_producer_ext.rb:126:in `deliver_messages'
/usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-kafka-0.14.0/lib/fluent/plugin/out_kafka2.rb:270:in `write'
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:1133:in `try_flush'
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:1439:in `flush_thread_run'
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.11.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

It looks like `banzaicloud/fluentd:v1.11.2-alpine-2` should upgrade the fluent-plugin-kafka version to 0.14.1 (currently at 0.14.0).

I think we might need this commit in the kafka fluent plugin.
https://github.com/fluent/fluent-plugin-kafka/commit/7dd3b91284bbee4b4ce664b90cc61dd621683b18

**Expected behaviour**:
The messages should be sent to kafka.

**Steps to reproduce the bug**:
logging.yaml
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-crd
spec:
  fluentd:
    image:
      pullPolicy: Always
      repository: banzaicloud/fluentd
      tag: v1.11.2-alpine-2
    logLevel: debug
    resources:
      requests:
        memory: "2G"
      limits:
        memory: "2G"
  fluentbit:
    image:
      pullPolicy: Always
      repository: fluent/fluent-bit
      tag: 1.5.3-debug
  controlNamespace: logging
```
flow.yaml
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: kafka-flow
spec:
  filters:
    - tag_normaliser:
        format: k8s.spark-stg.${pod_name}
    - parser:
        #remove_key_name_field: true
        #reserve_data: true
        #key_name: tag
        parse:
          type: none
  match:
    - select:
        labels:
          centralized-logging: kafka
  outputRefs:
    - kafka-cluster-output
    - debug-file-output
```

file output yaml
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: debug-file-output
spec:
  file:
    path: /tmp/${tag}/%Y/%m/%d/%H.%M
    buffer:
      timekey: 1m
      timekey_wait: 10s
      timekey_use_utc: true
```

kafka output yaml
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
 name: kafka-cluster-output
spec:
 kafka:
   brokers: <server1>:9092,<server2>:9092,<server3>:9092
   default_topic: spark_on_k8s_logs
   format:
     type: json
   buffer:
     timekey: 5m
     timekey_wait: 30s
     timekey_use_utc: true
```

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2):
- Cloud-provider/provisioner eks
- logging-operator version (e.g. 2.1.1): 3.5.0
- Install method (e.g. helm or static manifests): manifests
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug
