### ISSUE TITLE
Loki output ability to set X-Scope-OrgId header

### ISSUE THREAD

**Issue by IbraheemAlSaady** [banzaicloud/logging-operator#613]
I'm using Loki with `auth_enabled = true`, therefor, I need to pass the set X-Scope-OrgId HTTP header for the auth to work.

**Suggestion**
As a suggestion on the helm chart, I was thinking something similar to this

```YAML
    clusterOutputs:
      - name: loki
        spec:
          loki:
            url: http://loki.logging:3100
            headers:
              x-scope-orgid: <Org ID>
            configure_kubernetes_labels: true
```

**Comment by ahma** [comment]
Hi @IbraheemAlSaady, you can use the tenant param for this.

**Comment by IbraheemAlSaady** [comment]
Hey @ahma, I tried to navigate the docs, but I found it a bit difficult to find things, could you please guide me through this? 
Should it be
```YAML
clusterOutputs:
      - name: loki
        spec:
          loki:
            url: http://loki.logging:3100 
            tenant: "ORG_ID"
            configure_kubernetes_labels: true
```

Also, where can I find the docs for that?

Thanks
