### ISSUE TITLE
Logs load not evenly distributed across all Fluentd instances

### ISSUE THREAD

**Issue by bygui86** [banzaicloud/logging-operator#661]
**Describe the bug**:
Right after the very first deployment, as Fluent-bit starts faster than Fluentd, all Fluent-bit see just the first Fluentd available (aka fluentd-0), resulting in a exclusive usage of that instance (ignoring other possible scaling ones).

To solve this, I restarted all Fluent-bit using following command:
```shell script
kubectl rollout restart daemonset logging-components-fluentbit -n logging
```
After restart all Fluentd were use properly.

Probably Fluent-bit uses the headless k8s service without periodically refreshing it?

**Expected behaviour**:
In any case, Fluent-bit should use all available Fluentd, no matter how many instances and no matter at which point of the deployment.

**Steps to reproduce the bug**:
1. deploy CRDs using static manifests
2. deploy operator using static manifests
3. deploy any kind of output and flow
4. deploy logging using following yaml:
```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-components
spec:
  enableRecreateWorkloadOnImmutableFieldChange: true
  controlNamespace: logging
  fluentbit:
    metrics:
      serviceMonitor: true
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        effect: NoSchedule
    positiondb:
      hostPath:
          path: "/var/log/fluentbit-dbs/"
          type: DirectoryOrCreate
    bufferStorageVolume:
      hostPath:
          path: "/var/log/fluentbit-buffers/"
          type: DirectoryOrCreate
  fluentd:
    scaling:
      replicas: 3
    metrics:
      serviceMonitor: true
    livenessDefaultCheck: true
```

**Environment details**:
- Kubernetes version:   v1.17.14
- Cloud-provider/provisioner:   GKE
- logging-operator version:   3.8.3
- Install method: static manifests
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by pepov** [comment]
You are right that this is not a good default behaviour and I beleive we can fix it by selecting a sane default for `net.keepalive_max_recycle` instead of letting it keep tcp connections alive indefinitely.

Until then please try setting `spec.fluentbit.network.keepaliveMaxRecycle` to a number that you see fit for your load.

see https://docs.fluentbit.io/manual/v/master/administration/networking#tcp-keepalive-recycling

**Comment by bygui86** [comment]
@pepov thanks for the suggestion!
So you mean that Fluent-bit refreshes the list of available Fluentd (possibly scaling up and down), but due to the fact that TCP connections are already opened and if in use they are kept alive indefinitely, Fluent-bit does not see newly available Fluentd.
Yeah this is not the best default behavior because this completely miss the scaling of Fluentd, especially for new instances.

**Comment by bygui86** [comment]
Ok maybe 1000 is a bit too much... trying with 500...

**Comment by panaji** [comment]
@bygui86 , did you resolve your issue? i'm facing similar problem w/ 1.7 even after setting net.keepalive_max_recycle to 50.

**Comment by bygui86** [comment]
@panaji actually not really.
From time to time it happens again.
I have 3 Fluentd and sometimes only one works :( normally only 2 of them work.
No matter how I set that parameter.

**Comment by pepov** [comment]
What does your `logging` configuration look like? Feel free to drop it into slack and continue discussion there https://banzaicloud.slack.com/

**Comment by panaji** [comment]
i post it in fluentbit slack: https://fluent-all.slack.com/archives/C0CTQGHKJ/p1614478379146300
LMK if you want me to post in the banzaicloud too

**Comment by pepov** [comment]
@panaji please if you can share your logging configuratio with something like `kubectl describe logging`

**Comment by panaji** [comment]
@pepov , im not using banzai cloud, so that command won't work for me ... as i searched online with my problem, i came across this thread and i thought i would give it a shot and posted it here ... anyway, here's my config:

**Comment by pepov** [comment]
What is your fluentd service spec looks like? Is it a headless service by any chance?

Have you tried disabling keepalive completely?

As an alternative you should be able to leverage the upstream feature of fluentbit: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/upstream-servers

The only caveat is that you have to restart your deamonset pods, but the logging operator has support for that as well.

**Comment by bygui86** [comment]
@pepov I'm using banzaicloud logging-operator.

my configuration is pretty simple:

                                                            |--> cloud storage
k8s logs --> fluent-bit --> fluentd --|
                                                            |--> loki

I searched for "Fluent-bit Upstream" in banzaicloud documentation but I found nothing, do you have a sample on how to configure this feature?
I think this would be really useful for my use case!

**Comment by pepov** [comment]
@bshifter can you help us out here with some docs, or if it's not available with an example on how to configure this?

**Comment by bshifter** [comment]
The logging/spec/fluentbit/enableUpstream option automatically generates the fluent-bit's upstream configurations by the logging/spec/fluentd/scaling/replicas. There is no other option to finetune upstreams at the moment.
If your fluentd instances are controlled by the logging-operator it's enough to set enableUpstream to true.

**Comment by bygui86** [comment]
@bshifter thanks for the info!
I will test this feature as soon as I can :)

**Comment by panaji** [comment]
@pepov ,
My destination (fluentd service) is not headless, it's the standard ClusterIP.
I haven't tried disabling keepalive completely. I think it will severely impact the performance, if connection has to be re-established every time.
The upstream servers you mentioned, it seems to list all the nodes in the config. I think that's meant if you have a predefined set of servers. In our case, my destination are ClusterIP service and there is also HPA to adapt the load.

**Comment by panaji** [comment]
i retested this ... i see the `"[upstream] KA count %i exceeded configured limit of %i: closing."` ...  so connection is definitely getting refresh
below is the destination's (fluentd) cpu usage as i increase the load ... so it seems like it's working

thanks @pepov

![image](https://user-images.githubusercontent.com/30275153/110181577-f99de700-7dc0-11eb-8365-c55b0264bb60.png)

**Comment by wlawton** [comment]
I'm also having this issue and would like to try setting the logging/spec/fluentbit/enableUpstream option but have no idea where to configure that. Please can someone provide advise on this point.

I'm deploying fluent-bit v1.7.4 via helm-chart version 0.15.8 and fluentd v1.12.3 via Bitnami helm-chart v3.6.7. My fluent-bit output is configured like this:
    [OUTPUT]
        Name          forward
        Match         *
        Host          "fluentd-headless"
        Port          "24224"
        Retry_Limit   False

**Comment by pepov** [comment]
It's the path to the configuration option in the logging resource. In yaml it should look like this:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  ...
spec:
  fluentbit:
    enableUpstream: true
```
