### ISSUE TITLE
HTTP status code: 500, message: rpc error: code = Unknown desc = Entry out of order

### ISSUE THREAD

**Issue by apmartins85** [banzaicloud/logging-operator#674]
Hi team, hope you are doing great!

I'm trying to use  multi-worker feature with loki, but for some reason (probably my mistake), I can't! [Source](https://grafana.com/docs/loki/latest/clients/fluentd/#multi-worker-usage) <br />

This is my scenario: 

- EKS v1.18.9-eks-d1db3c (8 nodes)
- logging-operator 3.8.3
- About 5 fluentd

My clusterFlow conf:
```
spec:
    filters:
   - record_modifier:
       records:
       - fluentd_worker: "#{worker_id}"
    - tag_normaliser: {}
    - parser:
        key_name: log
        parse:
          patterns:
          - format: json
            time_key: ""
          - format: none
          type: multi_format
        remove_key_name_field: true
        reserve_data: true
    globalOutputRefs:
    - loki-server
    match:
    - select: {}
```
My clusterOutput:
```
spec:
    loki:
      buffer:
        chunk_limit_size: 1M
        flush_at_shutdown: true
        flush_interval: 1s
        flush_mode: interval
        retry_forever: true
        retry_type: periodic
        retry_wait: 10s
        path: ${root_dir}/worker${worker index}/${plugin @id}/buffer
      configure_kubernetes_labels: true
      url: http://logs-loki
      labels:
        worker_id_key: fluentd_worker
```
My logging:
```
spec:
    controlNamespace: logging-system
    fluentbit:
      bufferStorage:
        storage.path: /buffers-fluentbit
      image:
        pullPolicy: Always
        repository: repo/dockerhub/fluent/fluent-bit
        tag: 1.6.10-debug
      inputTail:
        Exclude_Path: /var/log/containers/*_kube-system_*.log, /var/log/containers/*_istio-*.log
        Refresh_Interval: "30"
        storage.type: filesystem
      podPriorityClassName: kubernetes-addons-ds
      resources:
        limits:
          cpu: 250m
          memory: 256M
        requests:
          cpu: 200m
          memory: 200M
    fluentd:
      rootDir: /buffers
      podPriorityClassName: kubernetes-addons-ds
      scaling:
        replicas: 5
      workers: 5
```

Does it make any sense? (I'm sure, not!) To be honest, I don't know how to deal with it!
I basically got "entry out of order" message, simulating a loki outage to see the buffer behaviour. When I'm trying to see on grafana this outage period, I see no data.

Cheers guys!

**Comment by pepov** [comment]
@apmartins85 There are two issues with this:
- there was a bug around the multiworker configcheck that has already been fixed in master, you can try with the latest image
- Loki does not allow records with the same labels to overap at ingest, which may be the case for multi workers if one of the workers is a bit ahead of others. A possible solution could be to add a worker specific label, but I'm not sure whether we can do that. In general we don't really recommend using Loki through fluentbit/fluentd until they remove the ordering requirement for their ingest, see: https://grafana.com/docs/loki/latest/design-documents/2021-01-ordering-constraint-removal/?pg=blog

**Comment by suryapssv** [comment]
Hi Team,

We are forwarding logs from fluentd to loki and we are getting below error warning message in our /fluentd/out

We are running a fluentd instance with a single worker and we are using logging operator provided by banzai cloud.

**400 Bad Request entry with timestamp 2021-07-06 18:08:05.471144027 +0000 UTC ignored, reason: 'entry out of order' for stream:**

**Comment by pepov** [comment]
Hey, this goes back to fluentbit where the issue still exists: https://github.com/fluent/fluent-bit/issues/2748

**Comment by suryapssv** [comment]
@pepov Our setup: fluentbit ->fluentd->loki 
And we are using banzai cloud logging operator with  2 fluentd instances running and each instance with one worker (worker=0).
So in this case how can we provide a unique labels like hostname either in clusteroutput or flow to avoid 'out of order entry'.

**Comment by pepov** [comment]
You can add a record transformer filter in your flow to extract the hostname, just like in the official example: https://docs.fluentd.org/filter/record_transformer

Then you can extract that value from the record in your output as the loki plugin docs describes:
https://grafana.com/docs/loki/latest/clients/fluentd/#adding-labels

Also if you use multiple workers, or multiple flush threads, you have to take care of those as well:
https://grafana.com/docs/loki/latest/clients/fluentd/#multi-worker-usage
https://grafana.com/docs/loki/latest/clients/fluentd/#using-multiple-buffer-flush-threads

However, none of these will fix the original issue, that fluentbit will still be sending events out of order in certain cases that you cannot fix in fluentd.

**Comment by rajivml** [comment]
@pepov 

I am also trying to get pass this error from last 2-3 days but no luck, am also using the same tech stack i.e.  
banzai logging operator -> fluentBit -> Loki -> S3 (Ceph object store)

And this is my configuration, just one loki and fluentd pods are running with default configuration on single node k8's cluster (RKE2) 


[testadmin@server0 ~]$ kubectl -n cattle-logging-system get pods
NAME                                           READY   STATUS      RESTARTS   AGE
rancher-logging-66cf7b84b9-dcvl4               1/1     Running     0          46h
rancher-logging-fluentbit-v57vm                1/1     Running     0          46h
rancher-logging-fluentd-0                      2/2     Running     0          46h
rancher-logging-fluentd-configcheck-4d2aa5e1   0/1     Completed   0          65m

[testadmin@server0 ~]$ kubectl -n loki get pods
NAME       READY   STATUS    RESTARTS   AGE
loki-0     1/1     Running   0          21h

I went through the above suggested solution and have added worker_id and hostname but still no luck, as soon as an out of order even occurs, log ingestion is just getting stopped
https://github.com/banzaicloud/logging-operator/issues/674#issuecomment-876181733

Can you please review my configuration and let me know what's wrong with this config. 

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: loki-output
  namespace: cattle-logging-system
spec:
  loki:
    url: http://loki.loki.svc.cluster.local:3100
    configure_kubernetes_labels: true
    extract_kubernetes_labels: true
    tenant: "loki"
    buffer:
      tags: time, tag, $.kubernetes.container_name, $.kubernetes.namespace_name, $.kubernetes.pod_name, fluentd_worker
      timekey: 3m
      timekey_wait: 60s
      retry_forever: false
      retry_max_times: 2
    # extra_labels:
    #   logger: loki
    labels:
      hostname: hostname
      worker: worker
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: loki-flow
  namespace: cattle-logging-system
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: json
    - record_transformer:
        records:
        - worker: "#{worker_id}"
        - hostname: "#{Socket.gethostname}"
  match:
    - exclude:
        container_names:
          - istio-proxy
          - istio-init
    - exclude:
        namespaces:
          - fleet-system
          - cattle-gatekeeper-system
          - default
    - exclude:
        labels:
          app: csi-snapshotter
    - exclude:
        labels:
          app: csi-resizer
    - select: {}
  globalOutputRefs:
  - loki-output
```

**Comment by rajivml** [comment]
I have switched from S3 to PVC but even with PVC am still seeing out of order events

**Comment by rajivml** [comment]
@suryapssv did you had any success fixing the issue, if yes, can you please share the config change

**Comment by rajivml** [comment]
@pepov am I doing anything wrong with the above configuration , can you please review the same

**Comment by alfianabdi** [comment]
@rajivml  I ran across this issue as well, but using record transformation helps

Flow
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: infra-flow
  namespace: ingress-nginx
spec:
  match:
    - select:
        labels:
          "app.kubernetes.io/instance": "ingress-nginx"
          "app.kubernetes.io/component": "controller"
  filters:
    - tag_normaliser: {}
    - record_modifier:
        records:
          - fluentd_worker: '"#{worker_id}"'
          - fluentd_host: '"#{Socket.gethostname}"'
  localOutputRefs:
    - "infra-output"
```

Output
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: infra-output
  namespace: ingress-nginx
spec:
  loki:
    buffer:
      timekey: 15s
      timekey_wait: 15s
      timekey_use_utc: true
    #configure_kubernetes_labels: true
    extra_labels:
      job: fluentd
      logtype: application
    labels:
      container: $.kubernetes.container_name
      container_id: $.kubernetes.docker_id
      fluentd_worker: $.fluentd_worker
      fluentd_host: $.fluentd_host
      host: $.kubernetes.host
      namespace: $.kubernetes.namespace_name
      pod: $.kubernetes.pod_name
      pod_id: $.kubernetes.pod_id
    remove_keys: ["kubernetes"]
    tenant: <redacted>
    url: <redacted>
```
