### ISSUE TITLE
[filter] enhanceK8s can't fetch k8s namespace labels

### ISSUE THREAD

**Issue by CloudXiaobai** [banzaicloud/logging-operator#704]
Hey, guys! Logging-operator is a great project, and I have deployed them on our kubernetes.It saves me  lots of time to manage configration. But recently I have encountered a problem, the default plugin `enhanceK8s` can't parse the labels in kubernetes namespace, it's bothering me a lot.😔

**Describe the bug**:
I define a `globalFilters` in my logging.yaml, like this

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: cluster
  namespace: logging
spec:
  globalFilters:
    - enhanceK8s:
        kubernetes_url: "https://kubernetes.default.svc.cluster.local"
        verify_ssl: false
  fluentd:
```

And a `clusteflow` to record kubernetes fields, like this

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: loki-flow
  namespace: logging
spec:
  globalOutputRefs:
    - loki
  filters:
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: json
    - record_modifier:
        records:
        - label: "${[(record.dig('kubernetes', 'namespace_labels', 'app_kubernetes_io/zone') || 'noenv'), (record.dig('kubernetes', 'labels', 'app_kubernetes_io/name') || 'noapp'), (record.dig('kubernetes', 'labels', 'app') || 'nosvc')].join('_')}"
        - k8s_node: "${record.dig('kubernetes', 'host')}"
        - k8s_container_name: "${record.dig('kubernetes', 'container_name')}"
        - k8s_app_name: "${record.dig('kubernetes', 'labels', 'app_kubernetes_io/name')}"
        - k8s_svc_name: "${record.dig('kubernetes', 'labels', 'app')}"
        - k8s_project_name: "${record.dig('kubernetes', 'namespace_labels', 'app_kubernetes_io/project_name')}"
        - k8s_env_name: "${record.dig('kubernetes', 'namespace_labels', 'app_kubernetes_io/zone')}"
        - k8s_pod_name: "${record.dig('kubernetes', 'pod_name')}"
        - k8s_namespace_name: "${record.dig('kubernetes', 'namespace_name')}"
        - k8s_image_version: "${record.dig('kubernetes', 'labels', 'app_image_version')}"
        - k8s_std_collect: "${record.dig('kubernetes', 'labels', 'log-collect') or record.dig('kubernetes', 'namespace_labels', 'log-collect') or false}"
```

Finally, I got a full configuration ,like this

```
<source>
  @type forward
  @id main_forward
  bind 0.0.0.0
  port 24240
</source>
<filter **>
  @type enhance_k8s_metadata
  @id globalFilter:0
  kubernetes_url https://kubernetes.default.svc.cluster.local
  verify_ssl false
</filter>
<match **>
  @type label_router
  @id main
  metrics true
  <route>
    @label @9080e03fb77160512a9178b6d80c2548
    metrics_labels {"id":"clusterflow:logging:loki-flow"}
    <match>
      labels app.kubernetes.io/name:kubernetes-event-exporter
      namespaces logging
      negate false
    </match>
    <match>
      labels tier:control-plane
      namespaces kube-system
      negate false
    </match>
    <match>
      labels app.kubernetes.io/component:operator
      namespaces logging,monitoring
      negate false
    </match>
    <match>
      labels app:fake-log
      namespaces logging
      negate false
    </match>
  </route>
</match>
<label @9080e03fb77160512a9178b6d80c2548>
  <filter **>
    @type parser
    @id clusterflow:logging:loki-flow:0
    key_name message
    remove_key_name_field true
    reserve_data true
    <parse>
      @type json
    </parse>
  </filter>
  <filter **>
    @type record_modifier
    @id clusterflow:logging:loki-flow:1
    <record>
      label ${[(record.dig('kubernetes', 'namespace_labels', 'app_kubernetes_io/zone') || 'noenv'), (record.dig('kubernetes', 'labels', 'app_kubernetes_io/name') || 'noapp'), (record.dig('kubernetes', 'labels', 'app') || 'nosvc')].join('_')}
    </record>
    <record>
      k8s_node ${record.dig('kubernetes', 'host')}
    </record>
    <record>
      k8s_container_name ${record.dig('kubernetes', 'container_name')}
    </record>
    <record>
      k8s_app_name ${record.dig('kubernetes', 'labels', 'app_kubernetes_io/name')}
    </record>
    <record>
      k8s_svc_name ${record.dig('kubernetes', 'labels', 'app')}
    </record>
    <record>
      k8s_project_name ${record.dig('kubernetes', 'namespace_labels', 'app_kubernetes_io/project_name')}
    </record>
    <record>
      k8s_env_name ${record.dig('kubernetes', 'namespace_labels', 'app_kubernetes_io/zone')}
    </record>
    <record>
      k8s_pod_name ${record.dig('kubernetes', 'pod_name')}
    </record>
    <record>
      k8s_namespace_name ${record.dig('kubernetes', 'namespace_name')}
    </record>
    <record>
      k8s_image_version ${record.dig('kubernetes', 'labels', 'app_image_version')}
    </record>
    <record>
      k8s_std_collect ${record.dig('kubernetes', 'labels', 'log-collect') or record.dig('kubernetes', 'namespace_labels', 'log-collect') or false}
    </record>
  </filter>
```

As you can see, i have to parsing some namespace labels for my logs. But i can't find any namespace labels on loki.

![image](https://user-images.githubusercontent.com/2688646/112572286-d47f2000-8e24-11eb-9cbe-3c35a3794931.png)

**Expected behaviour**:

I try to use `fluent-plugin-kubernetes_metadata_filter` on fluentd configuration manually(Of course, I also changed the fluentd clusterroles), like this

```
<source>
  @type forward
  @id main_forward
  bind 0.0.0.0
  port 24240
</source>
<filter **>
  @type kubernetes_metadata
  @id globalFilter:0
</filter>
...
```

Finally, I got a right fields on loki, like this

![image](https://user-images.githubusercontent.com/2688646/112572226-b1ed0700-8e24-11eb-8cb0-a7bf9bd5d682.png)

So, What is the reason for not using kubernetes_metadata and introducing enhanceK8s? And how to make enhanceK8s support namespace labels.? thanks a lot.

**Environment details**:

- Kubernetes version:  v1.18.16
- Cloud-provider/provisioner: Self
- logging-operator version: 3.9.2
- Install method: static manifests

/kind bug
