### ISSUE TITLE
All logs not catched / sent using helm ?

### ISSUE THREAD

**Issue by liogate** [banzaicloud/logging-operator#722]
**Describe the bug**:
For test purposes, i'm trying to build a cluster with rke and banzaicloud with elasticsearch and s3 output. I'm using helm for deployment and everything looks fine, but no data is sent to any of my output endpoints. It seems helm ignore my filters or maybe something else.

I don't know if this is a real issue or a misconfiguration, but I think I've tried all scenarios 😅 

Thanks for your help !

**UPDATE :** My docker logs are in /data/docker/... I think this is the root cause of all my issues.
**UPDATE 2 :** Logs are stored in /var/log/containers. My local setup is working, but on my remote server with the same config, nothing happend. So I've checked my inotify settings...
`cat /proc/sys/fs/inotify/max_user_instances` --> 8192
`cat /proc/sys/fs/inotify/max_user_watches` --> 524288

**UPDATE 3 :** I've rebooted the entire cluster, and my logs are not pushed...

```
k -n logging logs logging-operator-logging-fluentbit-pnmrl             
Fluent Bit v1.6.10
* Copyright (C) 2019-2020 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2021/04/22 13:36:41] [ info] [engine] started (pid=1)
[2021/04/22 13:36:41] [ info] [storage] version=1.0.6, initializing...
[2021/04/22 13:36:41] [ info] [storage] root path '/buffers'
[2021/04/22 13:36:41] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/04/22 13:36:41] [ info] [storage] backlog input plugin: storage_backlog.1
[2021/04/22 13:36:41] [ info] [input:storage_backlog:storage_backlog.1] queue memory limit: 4.8M
[2021/04/22 13:36:41] [ info] [filter:kubernetes:kubernetes.0] https=1 host=kubernetes.default.svc port=443
[2021/04/22 13:36:41] [ info] [filter:kubernetes:kubernetes.0] local POD info OK
[2021/04/22 13:36:41] [ info] [filter:kubernetes:kubernetes.0] testing connectivity with API server...
[2021/04/22 13:37:01] [ info] [filter:kubernetes:kubernetes.0] Wait 30 secs until DNS starts up (1/6)
[2021/04/22 13:37:37] [ info] [filter:kubernetes:kubernetes.0] API server connectivity OK
[2021/04/22 13:37:37] [ info] [sp] stream processor started
```

**Expected behaviour**:
I'm using for one of my output spec wrong credentials attentionally to expect a problem to be rised by the operator. But nothing happens. I've followed all of your troubleshooting guideline but I'm still stuck.

**Steps to reproduce the bug**:

In a folder `apps`, I have `logging-operator.yaml` and `logging-operator-logging.yaml` .

<details><summary>All of my configs here</summary>

```yaml
# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: es-user
type: Opaque
data:
  elastic: dGVzdAo=
---
apiVersion: v1
kind: Secret
metadata:
  name: logging-s3
type: Opaque
data:
  accesskey: dGVzdAo=
  secretkey: dGVzdAo=
```

```yaml
# logging-operator-logging.yaml

# Default values for logging-operator-logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Reference name of the logging deployment
loggingRef: ""
# Disable configuration check before deploy
flowConfigCheckDisabled: false
# Use static configuration instead of generated config.
flowConfigOverride: ""

nameOverride: ""
fullnameOverride: ""

# If an immutable field is changed, delete the existing resource
# and recreate it with the new configuration.
enableRecreateWorkloadOnImmutableFieldChange: true

# Fluent-bit configurations https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/#fluent-bit-spec
fluentbit:
    bufferStorageVolume:
      hostPath:
        path: "" # leave it empty to automatically generate
    positiondb:
      hostPath:
        path: "" # leave it empty to automatically generate

#Node agent Definition
nodeAgents: {}
#  - name: win-agent
#    profile: windows
#    nodeAgentFluentbit:
#      daemonSet:
#        spec:
#          template:
#            spec:
#              containers:
#              - image: banzaicloud/fluentbit:1.7.3
#                name: fluent-bit
#      tls:
#        enabled: false
#  - name: linux-agent
#    profile: linux
#    nodeAgentFluentbit:
#      metrics:
#        prometheusAnnotations: true
#        serviceMonitor: false
#      tls:
#        enabled: false


# Fluentd configurations https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/#fluentd-spec
fluentd:
  scaling:
    replicas: 1
  disablePvc: true
  fluentOutLogrotate:
    enabled: true
    path: /fluentd/log/out
    age: "10"
    size: "10485760"
# 20Gi persistent storage is configured for fluentd by default.
# Here is an example, on how to override it:
#  bufferStorageVolume:
#    pvc:
#      spec:
#        accessModes:
#          - ReadWriteOnce
#        resources:
#          requests:
#            storage: 40Gi

# Enable secure connection between fluentd and fluent-bit
tls:
  enabled: false
  # Shared key for fluentd authentication
  sharedKey: ""
  fluentbitSecretName: ""
  fluentdSecretName: ""

# Limit namespaces from where to read Flow and Output specs
watchNamespaces: ["logging"]
# Control namespace that contains ClusterOutput and ClusterFlow resources
controlNamespace: "logging"

# defaultFlow
defaultFlow: {}

# defaultFlow
globalFilters: []

# ClusterFlows to deploy
# clusterFlows: []

# ClusterOutputs to deploy
# clusterOutputs: []

# Send all pod logs to kafka
clusterFlows:
  - name: all-pods
    match:
    - select: {}
    filters:
    - tag_normaliser: {}
    spec:
      globalOutputRefs:
        - s3-output
        - elasticsearch

clusterOutputs:
  - name: s3-output
    spec:
      s3:
        aws_key_id:
          valueFrom:
            secretKeyRef:
              name: logging-s3
              key: accesskey
        aws_sec_key:
          valueFrom:
            secretKeyRef:
              name: logging-s3
              key: secretkey
        s3_bucket: demo
        s3_region: eu-west-1
        s3_endpoint: 'https://minio:9200'
        force_path_style: 'true'
        path: logs/${tag}/%Y/%m/%d/
        buffer:
          timekey: 10s
          timekey_wait: 0s
          timekey_use_utc: true
  - name: elasticsearch
    spec:
      elasticsearch:
        host:  log.example.com
        port: 443
        scheme: https
        ssl_verify: true
        ssl_version: TLSv1_2
        user: rke_user
        password:
          valueFrom:
            secretKeyRef:
              name: es-user
              key: elastic
        buffer:
          timekey: 1m
          timekey_wait: 30s
          timekey_use_utc: true

```

```yaml
# Default values for logging-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/banzaicloud/logging-operator
  tag: 3.9.4
  pullPolicy: IfNotPresent

extraArgs: []
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

## Pod custom labels
##
podLabels: {}

annotations: {}

## Deploy CRDs used by Logging Operator.
##
createCustomResource: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

http:
  # http listen port number
  port: 8080
  # Service definition for query http service
  service:
    type: ClusterIP
    clusterIP: None
    # Annotations to query http service
    annotations: {}
    # Labels to query http service
    labels: {}

rbac:
  enabled: true
  psp:
    enabled: false

## SecurityContext holds pod-level security attributes and common container settings.
## This defaults to non root user with uid 1000 and gid 2000.	*v1.PodSecurityContext	false
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
##
podSecurityContext: {}
#  runAsNonRoot: true
#  runAsUser: 1000
#  fsGroup: 2000
securityContext: {}
#  allowPrivilegeEscalation: false
#  readOnlyRootFilesystem: true
  # capabilities:
  #   drop: ["ALL"]

## Operator priorityClassName
##
priorityClassName: {}

monitoring:
  # Create a Prometheus Operator ServiceMonitor object
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    metricRelabelings: []
    relabelings: []
```
</details>

```bash
helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
helm repo update
helm upgrade --install --create-namespace --namespace logging logging-operator banzaicloud-stable/logging-operator --set createCustomResource=false -f apps/logging-operator.yaml
helm upgrade --install --create-namespace --namespace logging logging-operator-logging banzaicloud-stable/logging-operator-logging -f apps/logging-operator-logging.yaml
kubectl apply -f secrets.yaml
kubectl -n logging apply -f - <<"EOF" 
apiVersion: apps/v1 
kind: Deployment
metadata:
 name: log-generator
spec:
 selector:
   matchLabels:
     app.kubernetes.io/name: log-generator
 replicas: 1
 template:
   metadata:
     labels:   
       app.kubernetes.io/name: log-generator
   spec:
     containers:
     - name: nginx
       image: banzaicloud/log-generator:0.3.2
EOF
```

**Additional context**:
I'm using a clean cluster with a classic volume provider and RKE on 2 nodes.

<details>
<summary>Here is outputs</summary>

```
k -n logging get clusterflows.logging.banzaicloud.io
NAME       ACTIVE   PROBLEMS
all-pods   true 


k -n logging get clusteroutputs.logging.banzaicloud.io
NAME               ACTIVE   PROBLEMS
s3-output        true
elasticsearch  true


kubectl get secret -n logging logging-operator-logging-fluentbit -o jsonpath="{.data['fluent-bit\.conf']}" | base64 --decode
[SERVICE]
    Flush        1
    Grace        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf
    Coro_Stack_Size    24576
    storage.path  /buffers

[INPUT]
    Name         tail
    DB  /tail-db/tail-containers-state.db
    Mem_Buf_Limit  5MB
    Parser  docker
    Path  /var/log/containers/*.log
    Refresh_Interval  5
    Skip_Long_Lines  On
    Tag  kubernetes.*
[FILTER]
    Name        kubernetes
    Kube_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Tag_Prefix  kubernetes.var.log.containers
    Kube_Token_File  /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_URL  https://kubernetes.default.svc:443
    Match  kubernetes.*
    Merge_Log  On

[OUTPUT]
    Name          forward
    Match         *
    Host          logging-operator-logging-fluentd.logging.svc
    Port          24240
    
    Retry_Limit  False

k -n logging exec -it logging-operator-logging-fluentd-0 ls /buffers
empty

k -n logging get pods
NAME                                                    READY   STATUS      RESTARTS   AGE
log-generator-857d975d6-fw97w                           1/1     Running     0          7h9m
logging-operator-9c48d444b-tc97p                        1/1     Running     0          7h14m
logging-operator-logging-fluentbit-c7cp2                1/1     Running     0          30m
logging-operator-logging-fluentbit-zxrqw                1/1     Running     0          30m
logging-operator-logging-fluentd-0                      2/2     Running     0          142m
logging-operator-logging-fluentd-configcheck-fbbb7a24   0/1     Completed   0          31m

k -n logging logs logging-operator-9c48d444b-tc97p
{"level":"info","ts":1619074977.0070052,"logger":"controllers.Logging","msg":"resource created","name":"logging-operator-logging-fluentbit","namespace":"logging","apiVersion":"v1","kind":"ServiceAccount"}
{"level":"info","ts":1619074977.0275683,"logger":"controllers.Logging","msg":"resource created","name":"logging-operator-logging-fluentbit","apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole"}
{"level":"info","ts":1619074977.042551,"logger":"controllers.Logging","msg":"resource created","name":"logging-operator-logging-fluentbit","apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding"}
{"level":"info","ts":1619074977.0505922,"logger":"controllers.Logging","msg":"resource created","name":"logging-operator-logging-fluentbit","namespace":"logging","apiVersion":"v1","kind":"Secret"}
{"level":"info","ts":1619074977.060866,"logger":"controllers.Logging","msg":"resource created","name":"logging-operator-logging-fluentbit","namespace":"logging","apiVersion":"apps/v1","kind":"DaemonSet"}
{"level":"info","ts":1619081672.2806096,"logger":"controllers.Logging","msg":"still waiting for the configcheck result..."}
{"level":"info","ts":1619081672.2847672,"logger":"controllers.Logging","msg":"there are pending configcheck pods, need to back off"}
{"level":"info","ts":1619081672.2920232,"logger":"controllers.Logging","msg":"there are pending configcheck pods, need to back off"}
{"level":"info","ts":1619081672.3141878,"logger":"controllers.Logging","msg":"there are pending configcheck pods, need to back off"}
{"level":"info","ts":1619081672.9903214,"logger":"controllers.Logging","msg":"there are pending configcheck pods, need to back off"}
{"level":"info","ts":1619081674.1668403,"logger":"controllers.Logging","msg":"there are running configcheck pods, need to back off"}
I0422 08:54:36.314354       1 request.go:645] Throttling request took 1.046779174s, request: GET:https://10.43.0.1:443/apis/node.k8s.io/v1?timeout=32s
I0422 08:54:53.691081       1 request.go:645] Throttling request took 1.046024814s, request: GET:https://10.43.0.1:443/apis/acme.cert-manager.io/v1?timeout=32s
I0422 08:55:04.357673       1 request.go:645] Throttling request took 1.045238821s, request: GET:https://10.43.0.1:443/apis/logging.banzaicloud.io/v1beta1?timeout=32s
```

</details>

**Environment details**:
- Kubernetes version (e.g. v1.15.2): Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): RKE
- logging-operator version (e.g. 2.1.1): 3.9.4
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: (already posted)

/kind bug
