### ISSUE TITLE
Lost logs occurs when reload config

### ISSUE THREAD

**Issue by seb783191** [banzaicloud/logging-operator#735]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
We use logging-operator in a multitenancy implementation with one Logging (in one controlNamespace) and multiples Flows and Outputs in multiple namespaces.
We use version `3.9.4` of log-collector helm chart.

We have 2 replicas of our fluentd StatefulSet.
There is no problem with multiples config (flows / outputs) from multiples namespaces at runtime.

But when a new flow/output comes up in another namespace (and the configcheck success), the config of fluentd's pods are reloaded and the problem happens.

Use Case :

Here is the log of the config-reloader pod (jimmidyson/configmap-reload:v0.4.0) :
2021/05/11 06:51:21 config map updated
2021/05/11 06:51:21 performing webhook request (1/1)
2021/05/11 06:51:21 successfully triggered reload

This reload produces a hole in other namespaces logs ingestion :

At 11/May/2021:06:4 : OK
- Application log count : 335
- Fluentd Output log count (logstash in a file) : 335

At 11/May/2021:06:5 : Not OK
- Application log count : 332
- Fluentd Output log count (logstash in a file) : 319

We see that for the ten minutes in relation with the config reload, 13 logs are lost.

Did you already solve this, or do you have a recommandation ?

Regards

Hole seen also in kibana output :
![reload_config](https://user-images.githubusercontent.com/57069180/117839708-c3c32600-b27b-11eb-82de-81f0f4e972af.png)
![kibana_hole](https://user-images.githubusercontent.com/57069180/117839712-c45bbc80-b27b-11eb-9e36-43cf49633d95.png)

**Expected behaviour**:
No log lost

**Steps to reproduce the bug**:
Install the operator, install a flow and an output in one namespace. Check output.
Install a flow and an output in another namespace.
Config is reloaded and problem happens

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.19.0+2f3101c
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): OpenShift
- logging-operator version (e.g. 2.1.1): 3.9.4
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

Our Logging yaml :

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ include "log-collector.fullname" . }}
  labels:
    {{- include "log-collector.labels" . | nindent 4 }}
spec:
  controlNamespace: {{ .Release.Namespace }}
  fluentbit:
    metrics:
      serviceMonitor: true
    security:
      securityContext:
        privileged: true
  fluentd:
    metrics:
      serviceMonitor: true
    logLevel: info
```
