### ISSUE TITLE
Collect systemd (journald) logs or allow full configuration of fluent-bit inputs

### ISSUE THREAD

**Issue by iridian-ks** [banzaicloud/logging-operator#759]
**Is your feature request related to a problem? Please describe.**

fluent-bit is already running as a daemonset on every node. fluent-bit also supports collecting systemd logs. It seems wasteful to have to run a second fluent-bit/fluentd daemonset outside of the operator to collect this.

**Describe the solution you'd like**

A boolean flag to enable collecting systemd logs at the fluent-bit (Logging) level.

A second boolean flag at the ClusterFlow level to designate which flows will want to collect journald logs.

**Describe alternatives you've considered**

Running a second fluent-bit/fluentd stack in the cluster.

**Additional context**

I am willing to make these changes myself. I believe I've located where in the code I might need to make these updates.

Open to discussion on the current plan I've outlined.

EDIT:

I should also note, that these features should be optional as it's clearly not widely needed. The features added should be turned off by default.

For example, if instead of specifically adding only systemd support we make it so we add arbitrary input support and use custom fields to capture and route logs (and remove those fields after a flow receives it).

**Example for Systemd specific**

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-simple
spec:
  fluentd: {}
  fluentbit:
    systemd:
      enabled: true
      # other systemd specific config
  controlNamespace: logging
```

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-sample
  namespace: default
spec:
  # could be here
  systemd: true
  filters:
    - parser:
        remove_key_name_field: true
        parse:
          type: nginx
    - tag_normaliser:
        format: ${namespace_name}.${pod_name}.${container_name}
  localOutputRefs:
    - s3-output
  match:
    # or  maybe reuse this
    - select:
         systemd: true
    - select:
        labels:
          app: nginx
```

**Example for custom input**

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default-logging-simple
spec:
  fluentd: {}
  fluentbit:
    inputs:
      - systemd:
           name: my-systemd
           enabled: true
          # other systemd specific config
  controlNamespace: logging
```

```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-sample
  namespace: default
spec:
  # could be like this
  inputs:
    - name: my-systemd
  filters:
    - parser:
        remove_key_name_field: true
        parse:
          type: nginx
    - tag_normaliser:
        format: ${namespace_name}.${pod_name}.${container_name}
  localOutputRefs:
    - s3-output
  match:
    # or  maybe reuse this
    - inputs:
         name: my-systemd
    - select:
        labels:
          app: nginx
```

The latter solution seems more elegant and should prevent related tickets from coming up. Anything supported in fluent-bit proper would be supported.
