### ISSUE TITLE
parser multiline generating fluentd config with escape characters

### ISSUE THREAD

**Issue by mfbrj** [banzaicloud/logging-operator#802]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
When using parser `multiline`, the logging operator generates the `format_firstline` parameter with escape characteres. This seems to disturb the parser, since only the firstline seems to be parsed.

I'm using the following ClusterFlow:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: java
  namespace: cattle-logging-system
spec:
  filters:
    - parser:
        parse:
          type: multiline
          # Reference: https://docs.fluentd.org/parser/multiline#java-stacktrace-log
          format_firstline: /^\S+\d{2}:\d{2}:\d{2},\d{3}/
          multiline:
            - /^\S+\d{2}:\d{2}:\d{2},\d{3} (?<level>\S+) \s*\[(?<class>.*)\] \((?<thread>.*)\) (?<message>.*)/
        reserve_data: true
        remove_key_name_field: true
        reserve_time: true
    - record_transformer:
        records:
        - flow: "java"
    - tag_normaliser:
        format: k8s.${namespace_name}.${labels.app}
  globalOutputRefs:
    - ssr-es
  match:
    - select:
        namespaces:
          - some-namespace
```

The log entry:
```
[0m[33m03:31:59,449 WARN  [com.arjuna.ats.jta] (Periodic Recovery) ARJUNA016009: Caught:: java.lang.NullPointerException
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.xaRecoverySecondPass(XARecoveryModule.java:738)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.bottomUpRecovery(XARecoveryModule.java:519)
	at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkSecondPass(XARecoveryModule.java:270)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:816)
	at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:382)
```

**Expected behaviour**:
The parser should result these key/values:

Key | Value
-- | --
level|WARN
class|com.arjuna.ats.jta
thread|Periodic Recovery
message|ARJUNA016009: Caught:: java.lang.NullPointerException at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.xaRecoverySecondPass(XARecoveryModule.java:738) at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.bottomUpRecovery(XARecoveryModule.java:519) at com.arjuna.ats.internal.jta.recovery.arjunacore.XARecoveryModule.periodicWorkSecondPass(XARecoveryModule.java:270) at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:816) at com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:382)
 
**Steps to reproduce the bug**:
1. Use clusterflow yml and log entry of the **Describe the bug** section;
2. See the log parsed with these key/values.

Key | Value
-- | --
level|WARN
class|com.arjuna.ats.jta
thread|Periodic Recovery
message|ARJUNA016009: Caught:: java.lang.NullPointerException

**Additional context**:
The config snnipet generated by operator, with escape characters in `format_firstline` parameter:
```
    <filter **>
      @type parser
      @id clusterflow:cattle-logging-system:java:0
      key_name "log"
      remove_key_name_field true
      reserve_data true
      reserve_time true
      <parse>
        @type "multiline"
        format1 /^\S+\d{2}:\d{2}:\d{2},\d{3} (?<level>\S+) \s*\[(?<class>.*)\] \((?<thread>.*)\) (?<message>.*)/
        format_firstline "/^\\S+\\d{2}:\\d{2}:\\d{2},\\d{3}/"
      </parse>
    </filter>

```

**Environment details**:
- Kubernetes version: `v1.20.9`
- Cloud-provider/provisioner: Rancher 2.5.9 in vSphere 6.5 on premise
- logging-operator version: rancher/mirrored-banzaicloud-logging-operator:3.9.4
- Install method: Helm on Rancher Apps & Marketplace 
- Logs from the misbehaving component (and any other relevant logs): there is no errors on logs
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: shown on **Describe the bug**:
section.

/kind bug

**Comment by mfbrj** [comment]
I think the problem are the quotes generated on `format_firstline` parameter. I tried the yaml below (snipet) to avoid the double slash `\\`:
```
spec:
  filters:
    - parser:
        parse:
          type: multiline
          format_firstline: /[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}/
          multiline:
            - /^\S+\d{2}:\d{2}:\d{2},\d{3} (?<level>\S+) \s*\[(?<class>.*)\] \((?<thread>.*)\) (?<message>.*)/
```
Which generates the following fluentd config:
```
    <filter **>
      @type parser
      @id clusterflow:cattle-logging-system:java:0
      key_name "log"
      remove_key_name_field true
      reserve_data true
      reserve_time true
      <parse>
        @type "multiline"
        format1 /^\S+\d{2}:\d{2}:\d{2},\d{3} (?<level>\S+) \s*\[(?<class>.*)\] \((?<thread>.*)\) (?<message>.*)/
        format_firstline "/[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}/"
      </parse>
    </filter>
```
Unfortunally doesn't work. I get the same behaviour.
