### ISSUE TITLE
`no implicit conversion of nil into Hash` error from `fluent-plugin-label-router`

### ISSUE THREAD

**Issue by akhalyavka** [banzaicloud/logging-operator#825]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
After upgrading operator image to `3.14` and fluentd image to `v1.13.3-alpine-1` we started to get errors in fluentd logs:
```
2021-09-09 18:26:32 +0000 [warn]: #0 send an error event stream to @ERROR: error_class=TypeError error="no implicit conversion of nil into Hash" location="/usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-label-router-0.2.9/lib/fluent/plugin/out_label_router.rb:82:in `merge'" tag="kubernetes.var.log.containers.foobar.log"
```

**Expected behaviour**:
No errors.

**Additional context**:
The issue is already reported in https://github.com/banzaicloud/fluent-plugin-label-router/issues/16 but I guess that repo does not get as much attention as this one.

Our `Logging` resource:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging
spec:
  enableRecreateWorkloadOnImmutableFieldChange: true
  controlNamespace: logging
  globalFilters:
    - dedot:
        de_dot_nested: true
  defaultFlow:
    globalOutputRefs:
      - es-common
    filters:
      - parser:
          remove_key_name_field: true
          replace_invalid_sequence: true
          emit_invalid_record_to_error: false
          key_name: log
          reserve_data: true
          parse:
            type: json
      - detectExceptions:
          multiline_flush_interval: '0.1'
          message: log
  fluentd:
    metrics:
      prometheusAnnotations: true
    image:
      repository: redacted.dkr.ecr.us-east-1.amazonaws.com/banzaicloud/fluentd
      tag: v1.13.3-alpine-1
      pullPolicy: IfNotPresent
    configCheckResources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 32Mi
    configReloaderImage:
      repository: redacted.dkr.ecr.us-east-1.amazonaws.com/jimmidyson/configmap-reload
      tag: v0.4.0
      pullPolicy: IfNotPresent
    configReloaderResources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 64Mi
    configCheckAnnotations:
      sidecar.istio.io/inject: "false"
    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 512Mi
    security:
      podSecurityPolicyCreate: false
      securityContext:
        allowPrivilegeEscalation: false
        runAsGroup: 1000
        capabilities:
          drop:
            - all
        readOnlyRootFilesystem: false
      serviceAccount: fluentd
    labels:
      ignore-psp-readonlyrootfilesystem: "true"
      ignore-psp-allowprivilegeescalationcontainer: "true"
  fluentbit:
    image:
      repository: redacted.dkr.ecr.us-east-1.amazonaws.com/fluent/fluent-bit
      tag: 1.8.5
      pullPolicy: IfNotPresent
    bufferStorageVolume:
      hostPath:
        path: ""  # leave it empty to automatically generate
    positiondb:
      hostPath:
        path: ""  # leave it empty to automatically generate
    metrics:
      prometheusAnnotations: true
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    security:
      podSecurityPolicyCreate: false
      securityContext:
        allowPrivilegeEscalation: false
        runAsGroup: 1000
        capabilities:
          drop:
            - all
        readOnlyRootFilesystem: false
      serviceAccount: fluentbit
```

**Environment details**:
- Kubernetes version (e.g. v1.15.2): `v1.20.7`
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): `3.14`
- Install method (e.g. helm or static manifests): operator installed via helm + static `Logging` resource
- Logs from the misbehaving component (and any other relevant logs): in the bug description

/kind bug
