### ISSUE TITLE
[Question] Fluentd scaling with AZ-bound storage

### ISSUE THREAD

**Issue by jaimehrubiks** [banzaicloud/logging-operator#832]
Hello,

I want to ask the community about how you are handling using multiple replicas of Fluentd when using something like EBS, where volumes are bound to the availability zone. 

I see this issue was never addressed https://github.com/banzaicloud/logging-operator/issues/801

And I also see that "multi" group support is only available for fluentbit with the "Node Agents"

So the only thing left would be to impose a pod affinity rules with something like

```
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - fluentd
            topologyKey: topology.kubernetes.io/zone
```

But I don't think that is supposed to be used like that, and that is why [Topology Spread Constrains ](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/)are for 

If any of you could share a clue I would appreciate it
