### ISSUE TITLE
The cluster role for enhanceK8s needs get for pods

### ISSUE THREAD

**Issue by dbason** [banzaicloud/logging-operator#862]
**Describe the bug**:
Using the rbac generated when enhanceK8s is enabled as a global filter doesn't currently work

**Expected behaviour**:
The filter to add the metadata

**Steps to reproduce the bug**:
Enable enhanceK8s global filter:
```
  globalFilters:
  - enhanceK8s:
      ca_file: {}
      client_cert: {}
      client_key: {}
      in_namespace_path:
      - $.kubernetes.namespace_name
      in_pod_path:
      - $.kubernetes.pod_name
```

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.20
- Logs from the misbehaving component (and any other relevant logs):
-Fluentd logs message similar to the following:
```
2021-10-20 03:00:38 +0000 [warn]: #0 send an error event to @ERROR: error_class=Kubeclient::HttpError error="HTTP status code 403, pods \"frontend-5c4745dfdb-x42zj\" is forbidden: User \"system:serviceaccount:opni:opni-demo-fluentd\" cannot get resource \"pods\" in API group \"\" in the namespace \"default\" for GET /api/v1/namespaces/default/pods/frontend-5c4745dfdb-x42zj" location="/usr/lib/ruby/gems/2.7.0/gems/kubeclient-4.9.1/lib/kubeclient/common.rb:130:in `rescue in handle_exception'" tag="kubernetes.var.log.containers.frontend-5c4745dfdb-x42zj_default_server-5c2f97e933743cd59f25797fe7da44710cf2860e4eab77d551baea6585af8d08.log" time=2021-10-20 03:00:38.026454896 +0000
```

/kind bug
