### ISSUE TITLE
ImagePullSecrets for config-reload not used

### ISSUE THREAD

**Issue by skaffille** [banzaicloud/logging-operator#880]
**Describe the bug**:
We have a private container registry, which is the only registry we are allowed to pull certain images from.
We provided the imagePullSecrets configuration for fluentd.configReloaderImage on the logging CRD and installed it with the logging operator 3.15.0.

For fluentbit the imagePullSecrets configuration is reflected in the DaemonSet ...

**Expected behaviour**:
The statefulset for the fluentd has the corresponding imagePullSecret set and the image can be pulled from a private registry

**Steps to reproduce the bug**:
Use a private registry for the required containers.
Configure a secret to pull those images from the registry.
Create a logging configuration referencing the secret.
Install the logging configuration.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.22.3
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): custom
- logging-operator version (e.g. 2.1.1): 3.15.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
The container runtime complains that it is not authenticated due to the missing secret ...
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-infrastructure
spec:
  [...]
  fluentd:
    configReloaderImage:
      repository: <private-reg>
      imagePullSecrets:
        - name: <private-reg>-cred
```

/kind bug
