### ISSUE TITLE
Azure AKS log transfer to ElasticSearch

### ISSUE THREAD

**Issue by g-traveller** [banzaicloud/logging-operator#913]
Hi, Team,

The aks logs in container logs looks like:
```
2022-01-19T01:44:16.734137243Z stdout F {"timestamp":"2022-01-19T01:44:16.733Z","level":"INFO","thread":"http-nio-8080-exec-2","logger":"com.test.airlineapi.controller.AirlineApiController","message":"airline-api logging test: 88","context":"default"}
```
From the Fluentd log, it will send logs to ES as below, it results in the field "timestamp" missing from json.
```
{
   "stream":"stdout",
   "logtag":"F",
   "kubernetes": { ... }
   "message":"{\"timestamp\":\"2022-01-19T02:40:39.838Z\",\"level\":\"INFO\",\"thread\":\"http-nio-8080-exec-8\",\"logger\":\"com.test.airlineapi.controller.AirlineApiController\",\"message\":\"airline-api stop logging 2022-01-19T02:40:39.838966\",\"context\":\"default\"}"
}
```
If there is way to set timestamp field for those AKS log format, below attachment is generated flutend configuration.
[fluentd.txt](https://github.com/banzaicloud/logging-operator/files/7894112/fluentd.txt)

Thanks

**Comment by Ancitik** [comment]
Hi @g-traveller , if you are using the Flow CRD to create the logging stream, you can use `kube_events_timestamp` to create a `@timestamp` field in your records. 

Here is my code using the logging-operator-logging Helm chart:
```
clusterFlows:
  - name: all-pods
    spec:
      globalOutputRefs:
        - elasticsearch
      filters:
        - kube_events_timestamp:
            timestamp_fields:
              - "event.eventTime"
              - "event.lastTimestamp"
              - "event.firstTimestamp"
            mapped_time_key: "@timestamp"
```

And you can find here the reference: https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/filters/kube_events_timestamp/
