### ISSUE TITLE
Parser: pass configuration object

### ISSUE THREAD

**Issue by kwinkel** [banzaicloud/logging-operator#929]
**Is your feature request related to a problem? Please describe.**
When using not included plugins it is not a great experience using existing fields of the Flow/ClusterFlow CRD to configure any custom plugin.

**Describe the solution you'd like**
Please provide a CRD field for parsers to allow a configuration like this:
```yaml
spec:
  filters:
    - parser:
        parse:
          type: myplugin
          configuration: |
            myconfkey somevalue,someothervalue
```

**Describe alternatives you've considered**
Currently I'm using the `expression` field which limits custom plugins to use the CRD. This solution is very limited.
