### ISSUE TITLE
Cannot collect logs from log files with root permission

### ISSUE THREAD

**Issue by hahawu42** [banzaicloud/logging-operator#972]
**Describe the bug**:
I am running logging operator 3.17.0 on k8s.
Logging k8s resources from /var/log/... works perfectly but I also need to log files directly from the VM (e.g. /var/log/auth.log).
I am using the inputTail plugin specifying the files I need to log.
fluentbit shows the log message: 
```
Fluent Bit v1.8.9
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io
...
[date time] [error] [plugins/in tail/tail file.c:810 errno=13] Permission denied
[date time] [error] [input:tail:tail.0] cannot open /var/log/auth.log
```

As the /var/log/auth.log owner is root I configured the fluentbit container to run with root privileges (see referenced YAML file).
But even though the container runs as root user I receive the same log messages in fluentbit, showing permission denied.
Perhaps the fluent-bit.exe in the container is not executed as root but in the Dockerfile of fluentbit I didn't find with which user the .exe is run.

**Expected behaviour**:
I expect fluentbit to get the logs from /var/log/auth.log file

**Steps to reproduce the bug**:
Install k8s cluster
Install logging operator
Configure logging resource
Check fluentbit logs

**Environment details**:
- Kubernetes version v1.18.9
- Self-managed k8s cluster
- logging-operator version 3.17.0
- Install method: static manifests
- Logs from fluentbit (see above)
- logging resource definition:

```
kind: logging
metadata:
  name: logging
spec:
  controlNamespace: logging
  fluentbit:
    image:
      repository: your_fluentbit_image_repo # I am using  official images but a private repo
      tag: '1.8.9'
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi
    metrics:
      serviceMonitor: false
      prometheusRules: false
      serviceMonitorConfig: {}
    security:
      serviceAccount: fluent-bit
      podSecurityPolicyCreate: false
      roleBasedAccessControlCreate: true
      podSecurityContext:
        runAsNonRoot: false
        runAsUser: 0
    inputTail:
      Path: /var/log/auth.log
      Path_Key: /var/log/auth.log
      Parser: json
      Buffer_Chunk_Size: 1M
      Buffer_Max_Size: 1M
      Mem_Buffer_Limit: 32M
      Refresh_Interval: "10"
  fluentd:
    image:
      repository: your_fluentd_repo # I am using  official images but a private repo
      tag: 'v1.14.4-alpine-1'
    configReloaderImage:
      respository: your_config_reloader_repo # I am using  official images but a private repo
      tag: 'v0.5.0'
    logLevel: info
    ...further fluentd specs...
```

/kind bug
